export default {
    requestDateTime: null,
    channelName: null,
    jvmName: null,
    requestUrl: null,
    maxAge: 346644,
    contentExpiry: 'Fri Mar 31 2017 08:55:00 AM',
    type: 'homePageGridContent',
    disclaimer: 'Live publish for content grid',
    timerEnabled: true,
    gridContents: null,
    massagedData: [
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '01_Worthington-pants_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/boots-for-her.jpg',
            imageAlt: '01_Worthington-pants_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/worthington-pants-women/N-bwo3xZ7zZ1z140w7?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '02_men-graphict-shirts_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/boys-novelty-tees.jpg',
            imageAlt: '02_men-graphict-shirts_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/mens-graphic-tees/N-bwo3yDgl5k1h?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '03_baby-okiedokie_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/cooks-coffee-maker-or-griddle.jpg',
            imageAlt: '03_baby-okiedokie_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/okie-dokie-baby/N-bwo41Z6q?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '05_women-tees_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/cooks-slow-cooker-or-blender.jpg',
            imageAlt: '05_women-tees_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/womens-tops/N-bwo3xD1nnuja?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '06_men-SJB-polos_030917',
            imageSrc: "http://m-dt-test3.jcpenney.com/mobile/images/men's-sjb.jpg",
            imageAlt: '06_men-SJB-polos_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/mens-shirts/N-bwo3yD1nohp5?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '13_womens-active-tanks_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/womens-sjb-long-sleeve-tee.jpg',
            imageAlt: '13_womens-active-tanks_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/tank-tops-shirts-tops-womens-activewear/N-bwo3xD1noph0Z1z0pivvZ1z140sb?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '17_juniors-dresses_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/juniors-arizona-jeans.jpg',
            imageAlt: '17_juniors-dresses_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/teen-dresses/N-1b0zt0pD1nohos?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '18_men-collectionbymichaelstrahan_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/kids-arizona-jeans.jpg',
            imageAlt: '18_men-collectionbymichaelstrahan_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/collection-by-michael-strahan-men/N-bwo3yZ62r?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '20_Tfal-cookware_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/cooks-coffee-maker-or-griddle.jpg',
            imageAlt: '20_Tfal-cookware_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/cookware/N-bwo3vD1nohox?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '21_juniors-AZ-denim-shorts_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/kids-arizona-jeans.jpg',
            imageAlt: '21_juniors-AZ-denim-shorts_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/juniors-shorts/N-1b0zt0pD1nopil?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '22_men-suits-sportcoats_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/stafford-dress-shirt.jpg',
            imageAlt: '22_men-suits-sportcoats_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/mens-suits-sport-coats/N-bwo3yD1nopeu?',
            dynamicUrl: false,
        },
        {
            type: 'ImageBannerWithOverlay',
            id: null,
            contentType: 'ImageBannerWithOverlay',
            desktopImageBannerDetails: null,
            overlay: 'n',
            offerId: '23_womens-Yuu-sandals_030917',
            imageSrc: 'http://m-dt-test3.jcpenney.com/mobile/images/xdiv-nike-shoes.jpg',
            imageAlt: '23_womens-Yuu-sandals_030917',
            openIn: '_self',
            windowHeight: '200',
            windowWidth: '100',
            link: null,
            pageURL: '/g/yuu-womens-sandals-flip-flops/N-bwo42D1nopjlZ1hg?',
            dynamicUrl: false,
        },
    ],
};
