const ZoneContentDataImage = {
    requestDateTime: null,
    channelName: null,
    jvmName: 'dtexpdv1l1j1_01',
    requestUrl: null,
    maxAge: 66628,
    contentExpiry: 'Thu Jan 26 2017 12:00:00 PM',
    allDay: false,
    type: 'Content-ZoneA',
    zoneType: 'image',
    imageBannerDetails: {
        type: null,
        contentType: 'MultiChannelSlotImageBanner',
        desktopImageDetails: {
            imageSrc: 'pg00001_mt00001_47100015.gif',
            imageAlt: '',
            imageUrl: '/g/view-all-accessories/N-bwo3yDgm42c8',
            dimensionId: null,
            analyticsTag: 'cm_re=HP-yodaXL-_-ZoneB-_-Zone B of home page',
        },
        mobileImageDetails: {
            imageSrc: 'pg00001_mt00001_47100015.gif',
            imageAlt: 'Mobile Zone A',
            imageUrl: '/g/shops/N-1az9fo4',
            dimensionId: '2840670868',
            analyticsTag: 'cm_re=HP-yodaXL-_-ZoneB-_-Zone B of home page',
        },
        tabletImageDetails: {
            imageSrc: 'pg00001_mt00001_47100015.gif',
            imageAlt: '',
            imageUrl: '/g/women/N-bwo3x?pageType=X2H2',
            dimensionId: '20000013',
            analyticsTag: 'cm_re=HP-yodaXL-_-ZoneB-_-Zone B of home page',
        },
        nativeAppsImageDetails: {
            imageSrc: 'Desktop_Home_Zone A_Image_Div 1_jewelry_01202017_0000_01262017_0000.jpg',
            imageAlt: 'Native Apps Alt Text',
            imageUrl: '/g/shops/N-1az9fo4',
            dimensionId: '2840670868',
        },
        extraLargeImageDetails: {
            imageSrc: 'Apps_Home_Zone_A_Image_Div_X_home_Page_04242017_1200_AM_04262017_1159_PM.gif',
            imageAlt: 'Zone B of home page',
            imageUrl: 'http://www;google.com',
            dimensionId: null,
            target: '_self',
            analyticsTag: 'cm_re=HP-yodaXL-_-ZoneB-_-Zone B of home page',
        },
        largeImageDetails: {
            imageSrc: 'Apps_Home_Zone_B_Image_Div_X_home_Page_04242017_1200_AM_04262017_1159_PM.gif',
            imageAlt: 'Zone B of home page',
            imageUrl: 'http://www;google.com',
            dimensionId: null,
            target: '_self',
            analyticsTag: 'cm_re=HP-yodaL-_-ZoneB-_-Zone B of home page',
        },
    },
    imageMapDetails: null,
};


/* for imagemap */
const ZoneContentDataImageMap = {
    requestDateTime: null,
    channelName: null,
    jvmName: 'dtexpdv1l1j1_01',
    requestUrl: null,
    maxAge: 45299,
    contentExpiry: 'Thu Jan 26 2017 12:00:00 AM',
    allDay: true,
    type: 'Content-ZoneA',
    imageBannerDetails: null,
    zoneType: 'imageMap',
    imageMapDetails: {
        contentType: 'MultiChannelSlotImageMap',
        type: null,
        desktopMapDetails: {
            image: 'HP_feature-YODA-Small-Banner1.jpg',
            imageAlt: 'image alt',
            map: null,
            imagemapArea: [
                {
                    alt: 'blush',
                    coords: '4,2,431,168',
                    link: '/mobile/gN-1az9fo4Dgnt5elZ1z0njxh?cm_re=HP-MW-_-c4-0306-_-now-trending---blush',
                    shape: 'rectangle',
                    target: '_self',
                },
                {
                    alt: 'test',
                    coords: '616,26,1082,112',
                    link: 'http://jcpenney.com',
                    shape: 'rect',
                    target: '_self',
                },
            ],
            imageUrl: 'Desktop_Home_Zone A_Image_Div 1_handbags_01202017_0000_01222017_0000.jpg',
            mediaUri: null,
        },
        mobileMapDetails: {
            image: 'HP_feature-YODA-Small-Banner1.jpg',
            imageAlt: 'image alt',
            map: null,
            imagemapArea: [
                {
                    alt: 'sfdsafsff',
                    coords: '94,79,141,78,142,113,97,113',
                    link: 'www.bestbuy.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asfdffd',
                    coords: '28,152,154,152,156,170,29,172',
                    link: 'www.jcp.com',
                    shape: 'poly',
                    target: '_self',
                },
            ],
            imageUrl: 'Desktop_Home_Zone A_Image_Div 1_for the home_01202017_0000_01312017_0000.jpg',
            mediaUri: null,
        },
        tabletMapDetails: {
            image: 'HP_feature-YODA-Small-Banner1.jpg',
            imageAlt: 'image alt',
            map: null,
            imagemapArea: [
                {
                    alt: 'asffdsfdsf',
                    coords: '669,263,785,264,779,349,669,344',
                    link: 'www.tablet.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asfsffd',
                    coords: '84,425,198,427,193,500,86,503',
                    link: 'www.test.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asffdsfdsf',
                    coords: '37,280,188,281,185,308,34,308',
                    link: 'www.talet.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asffdsfdsf',
                    coords: '212,277,367,278,366,306,213,308',
                    link: 'www.tabt.com',
                    shape: 'poly',
                    target: '_self',
                },
            ],
            imageUrl: 'Desktop_Home_Zone A_Image_Div 5_juniors_01202017_0000_01312017_0000.jpg',
            mediaUri: null,
        },
        nativeAppsMapDetails: {
            image: 'HP_feature-YODA-Small-Banner1.jpg',
            map: null,
            imagemapArea: [
                {
                    alt: 'test2',
                    coords: '30,18,552,142',
                    link: 'www.test2.com',
                    shape: 'rect',
                    target: '_self',
                },
            ],
            imageUrl: 'Desktop_Home_Zone A_Image_Div 1_kids_01202017_0000_01312017_0000.jpg',
            mediaUri: null,
        },
        extraLargeMapDetails: {
            image: 'HP_feature-YODA-Small-Banner1.jpg',
            imageAlt: 'image alt',
            map: null,
            imagemapArea: [
                {
                    alt: 'asffdsfdsf',
                    coords: '669,263,785,264,779,349,669,344',
                    link: 'www.tablet.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asfsffd',
                    coords: '84,425,198,427,193,500,86,503',
                    link: 'www.test.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asffdsfdsf',
                    coords: '37,280,188,281,185,308,34,308',
                    link: 'www.talet.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asffdsfdsf',
                    coords: '212,277,367,278,366,306,213,308',
                    link: 'www.tabt.com',
                    shape: 'poly',
                    target: '_self',
                },
            ],
            imageUrl: 'Desktop_Home_Zone A_Image_Div 5_juniors_01202017_0000_01312017_0000.jpg',
            mediaUri: null,
        },
        largeMapDetails: {
            image: 'HP_feature-YODA-Small-Banner1.jpg',
            imageAlt: 'image alt',
            map: null,
            imagemapArea: [
                {
                    alt: 'asffdsfdsf',
                    coords: '669,263,785,264,779,349,669,344',
                    link: 'www.tablet.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asfsffd',
                    coords: '84,425,198,427,193,500,86,503',
                    link: 'www.test.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asffdsfdsf',
                    coords: '37,280,188,281,185,308,34,308',
                    link: 'www.talet.com',
                    shape: 'poly',
                    target: '_self',
                },
                {
                    alt: 'asffdsfdsf',
                    coords: '212,277,367,278,366,306,213,308',
                    link: 'www.tabt.com',
                    shape: 'poly',
                    target: '_self',
                },
            ],
            imageUrl: 'Desktop_Home_Zone A_Image_Div 5_juniors_01202017_0000_01312017_0000.jpg',
            mediaUri: null,
        },
    },
};


/* for VisualNavigation */
const ZoneContentDataVisualNav = {
    requestDateTime: 'Tue Mar 07 17:28:18 CST 2017',
    channelName: 'EXPCOM-WEB',
    jvmName: null,
    requestUrl: 'http://localhost:8080/expcomm-api/j/department/N-1b0lvh6?op=visnavzone',
    contentExpiry: 'Thu Mar 9 2017 12:00:00 AM',
    allDay: false,
    maxAge: 0,
    type: 'visnavzone',
    imageBannerDetails: null,
    imageMapDetails: null,
    visualNavDetails: {
        imagesAvailable: true,
        visualNavHeader: 'test',
        visNavSlots: [
            {
                imageName: null,
                imageLink: null,
                imageAlt: null,
                openIn: null,
                windowHeight: null,
                windowWidth: null,
                isDynamic: null,
                h1title: 'Desktop_Home_Zone C_Image_Div 5_clearance_02022017_0000_02282017_0000.jpg',
                imagePath: 'http://s7d9.scene7.com/is/image/JCPenney//DP1212201317371926M',
                seoUrl: 'http://www.jcpenney.com/g/home-store/N-bwo3v?pageType=X2H2',
                departmentId: '2845660840',
                searchTerm: null,
                visNavType: 'Internal',
                slotId: 0,
                taggingValues: null,
                ppId: null,
            },
            {
                imageName: null,
                imageLink: null,
                imageAlt: null,
                openIn: null,
                windowHeight: null,
                windowWidth: null,
                isDynamic: null,
                h1title: '',
                imagePath: 'http://s7d9.scene7.com/is/image/JCPenney//DP0802201617141668M',
                seoUrl: 'http://www.jcpenney.com/g/bed-and-bath/N-bwo3w?pageType=X2H2',
                departmentId: null,
                searchTerm: 'jeans',
                visNavType: 'Internal',
                slotId: 0,
                taggingValues: null,
                ppId: null,
            },
        ],
    },
};

export default {
    ZoneContentDataImage,
    ZoneContentDataImageMap,
    ZoneContentDataVisualNav,
};
