export default {
    type: 'ImageBannerWithOverlay',
    id: null,
    contentType: 'ImageBannerWithOverlay',
    desktopImageBannerDetails: null,
    overlay: 'n',
    offerId: '01_ana-tee_051217',
    imageSrc: '/mobile/images/01_ana-tee_051217.jpg',
    imageAlt: 'ana tee',
    openIn: '_self',
    windowHeight: '200',
    windowWidth: '100',
    link: null,
    pageURL: '/g/ana-women/N-bwo3xZ3v',
    dynamicUrl: false,
    analyticsTag: 'cm_re=HP-DT-_-c2-_-First one|1|o',
    deviceType: {
        isDesktop: false,
        isMobile: true,
        isTablet: false,
    },
    isOverlay: true,
    currentIndex: 0,
};
