export default [
    {
        term: 'shirts',
        url: '/s/shirts?searchType=Predictive+Search&Ntt=shirts&predSearchTerm=shirts',
        depts: [
            {
                href: '/s/shirts/N-bwo3y?searchType=Predictive+Search&Ntt=shirts&departmentId=dept20000014&N=20000014&deptName=men&predSearchTerm=shirts',
                name: 'men',
                products: [
                    {
                        title: 'Levi\'s® 501® Original Fit Jeans',
                        imageId: 'DP0712201620395971C.tif',
                        productUrl: '/p/levis-501-original-fit-jeans/pp50010880054?pTmplType=regular&N=1633&searchTerm=levis 501 original fit jeans&catId=SearchResults&searchType=Predictive%20Search%7CProducts%7C3',
                        averageRating: '1.0',
                        totalReviewCount: '3',
                        totalColorCount: '2',
                        productCurSlotPrice: 'null',
                        productOrgSlotPrice: '$69.50 original',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: 'view price in bag',
                        productPromoMessage: null,
                    },
                    {
                        title: 'St. John\'s Bay Short Sleeve Solid Performance Pique Polo Shirt',
                        imageId: 'DP1222201617071550M.tif',
                        productUrl: '/p/st-johns-bay-short-sleeve-solid-performance-pique-polo-shirt/ppr5007146147?pTmplType=regular&N=20000014&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                        averageRating: '4.66',
                        totalReviewCount: '363',
                        totalColorCount: '30',
                        productCurSlotPrice: 'null',
                        productOrgSlotPrice: '$26',
                        productPromoMktgLabel: 'null',
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'Stafford® Travel Performance Pinpoint Oxford Dress Shirt',
                        imageId: 'DP0428201418374819C.tif',
                        productUrl: '/p/stafford-travel-performance-pinpoint-oxford-dress-shirt/16bb884?pTmplType=regular&N=20000014&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                        averageRating: '4.04',
                        totalReviewCount: '663',
                        totalColorCount: '4',
                        productCurSlotPrice: '$1,900.99 sale',
                        productOrgSlotPrice: '$4000 original',
                        productPromoMktgLabel: 'null',
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'Nike® Dri-FIT Short-Sleeve Tee - Big & Tall',
                        imageId: 'DP0131201720340605C.tif',
                        productUrl: '/p/nike-dri-fit-short-sleeve-tee-big-tall/pp5008050198?pTmplType=regular&N=20000014&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                        averageRating: '4.42',
                        totalReviewCount: '52',
                        totalColorCount: '16',
                        productCurSlotPrice: '$19.99 sale',
                        productOrgSlotPrice: '$25 original',
                        productPromoMktgLabel: 'null',
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'Stafford® Travel Performance Super Shirt',
                        imageId: 'DP1013201620303526C.tif',
                        productUrl: '/p/stafford-travel-performance-super-shirt/1cca9b9?pTmplType=regular&N=20000014&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                        averageRating: '4.32',
                        totalReviewCount: '1112',
                        totalColorCount: '6',
                        productCurSlotPrice: 'null',
                        productOrgSlotPrice: '$50',
                        productPromoMktgLabel: 'null',
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                ],
            },
            {
                href: '/s/shirts/N-bwo40?searchType=Predictive+Search&Ntt=shirts&departmentId=dept20000016&N=20000016&deptName=kids&predSearchTerm=shirts',
                name: 'kids',
                products: [
                    {
                        title: 'IZOD®  Stretch Piqué Polo - Boys 8-20 and Husky',
                        imageId: 'DP0710201720381954C.tif',
                        productUrl: '/p/izod-stretch-piqué-polo-boys-8-20-and-husky/ppr5007282059?pTmplType=regular&N=20000016&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                        averageRating: '4.82',
                        totalReviewCount: '11',
                        totalColorCount: '4',
                        productCurSlotPrice: 'null',
                        productOrgSlotPrice: '$20 - $22',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'IZOD® Stretch Piqué Polo - Boys 8-20 and Husky',
                        imageId: 'DP0710201720383390C.tif',
                        productUrl: '/p/izod-stretch-piqué-polo-boys-8-20-and-husky/ppr5007282061?pTmplType=regular&N=20000016&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                        averageRating: '5.0',
                        totalReviewCount: '7',
                        totalColorCount: '7',
                        productCurSlotPrice: 'null',
                        productOrgSlotPrice: '$20 - $22',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'Arizona Crochet Tunic Top - Girls\' 7-16 and Plus',
                        imageId: 'DP0620201720315001C.tif',
                        productUrl: '/p/arizona-crochet-tunic-top-girls-7-16-and-plus/ppr5007201624?pTmplType=regular&N=20000016&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                        averageRating: '4.71',
                        totalReviewCount: '7',
                        totalColorCount: '6',
                        productCurSlotPrice: '$9.99 - $11.99 sale',
                        productOrgSlotPrice: '$20 - $22 original',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'Arizona Hi-Lo Top w/ Necklace - Girls\' 7-16 and Plus',
                        imageId: 'DP0517201717091314M.TIF',
                        productUrl: '/p/arizona-hi-lo-top-w-necklace-girls-7-16-and-plus/ppr5007291424?pTmplType=regular&N=20000016&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                        averageRating: '4.91',
                        totalReviewCount: '11',
                        totalColorCount: '0',
                        productCurSlotPrice: '$14.99 - $17.99 sale',
                        productOrgSlotPrice: '$26 - $28 original',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                ],
            },
            {
                href: '/s/shirts/N-bwo41?searchType=Predictive+Search&Ntt=shirts&departmentId=dept20000017&N=20000017&deptName=baby&predSearchTerm=shirts',
                name: 'baby',
                products: [
                    {
                        title: 'Okie Dokie Graphic T-Shirt-Toddler Boys',
                        imageId: 'DP0615201717080083M.tif',
                        productUrl: '/p/okie-dokie-graphic-t-shirt-toddler-boys/ppr5007205487?pTmplType=regular&N=20000017&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                        averageRating: '5.0',
                        totalReviewCount: '2',
                        totalColorCount: '6',
                        productCurSlotPrice: '$4.99 sale',
                        productOrgSlotPrice: '$12 original',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'Okie Dokie Graphic T-Shirt-Toddler Girls',
                        imageId: 'DP0420201717100496M.tif',
                        productUrl: '/p/okie-dokie-graphic-t-shirt-toddler-girls/ppr5007204717?pTmplType=regular&N=20000017&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                        averageRating: '5.0',
                        totalReviewCount: '4',
                        totalColorCount: '5',
                        productCurSlotPrice: '$4.99 sale',
                        productOrgSlotPrice: '$12 original',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'Okie Dokie Long Sleeve Crew Neck T-Shirt-Toddler Girls',
                        imageId: 'DP0518201717073319M.tif',
                        productUrl: '/p/okie-dokie-long-sleeve-crew-neck-t-shirt-toddler-girls/ppr5007204718?pTmplType=regular&N=20000017&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                        averageRating: '5.0',
                        totalReviewCount: '3',
                        totalColorCount: '5',
                        productCurSlotPrice: '$4.99 sale',
                        productOrgSlotPrice: '$12 original',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                    {
                        title: 'Okie Dokie Tunic Top - Toddler Girls',
                        imageId: 'DP0504201700335864M.tif',
                        productUrl: '/p/okie-dokie-tunic-top-toddler-girls/ppr5007204720?pTmplType=regular&N=20000017&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                        averageRating: '5.0',
                        totalReviewCount: '1',
                        totalColorCount: '5',
                        productCurSlotPrice: '$4.99 sale',
                        productOrgSlotPrice: '$12 original',
                        productPromoMktgLabel: null,
                        productMapPriceDesc: null,
                        productPromoMessage: null,
                    },
                ],
            },
        ],
        products: [
            {
                title: 'Arizona Short-Sleeve Polo Shirt',
                imageId: 'DP0614201720330602C.tif',
                productUrl: '/p/arizona-short-sleeve-polo-shirt/pp5006870331?pTmplType=regular&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '4.54',
                totalReviewCount: '146',
                totalColorCount: '11',
                productCurSlotPrice: '$22,600 clearance',
                productOrgSlotPrice: '$50,750 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'St. John\'s Bay Short Sleeve Solid Performance Pique Polo Shirt',
                imageId: 'DP1222201617071550M.tif',
                productUrl: '/p/st-johns-bay-short-sleeve-solid-performance-pique-polo-shirt/ppr5007146147?pTmplType=regular&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '4.66',
                totalReviewCount: '363',
                totalColorCount: '30',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$26',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'IZOD®  Stretch Piqué Polo - Boys 8-20 and Husky',
                imageId: 'DP0710201720381954C.tif',
                productUrl: '/p/izod-stretch-piqué-polo-boys-8-20-and-husky/ppr5007282059?pTmplType=regular&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '4.82',
                totalReviewCount: '11',
                totalColorCount: '4',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$20 - $22',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Stafford® Travel Performance Pinpoint Oxford Dress Shirt',
                imageId: 'DP0428201418374819C.tif',
                productUrl: '/p/stafford-travel-performance-pinpoint-oxford-dress-shirt/16bb884?pTmplType=regular&searchTerm=shirts&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.04',
                totalReviewCount: '663',
                totalColorCount: '4',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$40 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
        ],
    },
    {
        term: 'shirts junior',
        url: '/s/shirts-junior?searchType=Predictive+Search&Ntt=shirts+junior&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short-Sleeve Polo Shirt',
                imageId: 'DP0614201720330602C.tif',
                productUrl: '/p/arizona-short-sleeve-polo-shirt/pp5006870331?pTmplType=regular&searchTerm=shirts junior&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '4.54',
                totalReviewCount: '146',
                totalColorCount: '11',
                productCurSlotPrice: '$9.99 sale',
                productOrgSlotPrice: '$18 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Arizona Short-Sleeve Polo Shirt - Juniors Plus',
                imageId: 'DP0512201717163195M.tif',
                productUrl: '/p/arizona-short-sleeve-polo-shirt-juniors-plus/pp5006870332?pTmplType=regular&searchTerm=shirts junior&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '4.54',
                totalReviewCount: '24',
                totalColorCount: '11',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$22 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Arizona Short-Sleeve V-Neck T-Shirt - Juniors',
                imageId: 'DP0628201720323822C.tif',
                productUrl: '/p/arizona-short-sleeve-v-neck-t-shirt-juniors/pp5008020004?pTmplType=regular&searchTerm=shirts junior&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '4.66',
                totalReviewCount: '448',
                totalColorCount: '20',
                productCurSlotPrice: '$5.99 - $6.99 sale',
                productOrgSlotPrice: '$14 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts junior&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
        ],
    },
    {
        term: 'shirts big',
        url: '/s/shirts-big?searchType=Predictive+Search&Ntt=shirts+big&predSearchTerm=shirts',
        products: [
            {
                title: 'Stafford® 3-pk. Heavyweight Cotton Crewneck T-Shirts - Big & Tall',
                imageId: 'DP0218201621270825C.tif',
                productUrl: '/p/stafford-3-pk-heavyweight-cotton-crewneck-t-shirts-big-tall/pp5006020212?pTmplType=regular&searchTerm=shirts big&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '4.9',
                totalReviewCount: '30',
                totalColorCount: '3',
                productCurSlotPrice: null,
                productOrgSlotPrice: '$40 - $44',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Stafford® 4-pk. Heavyweight V-Neck T-Shirts - Big & Tall',
                imageId: 'DP0819201318433293C.tif',
                productUrl: '/p/stafford-4-pk-heavyweight-v-neck-t-shirts-big-tall/pp5002910727?pTmplType=regular&searchTerm=shirts big&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '4.74',
                totalReviewCount: '171',
                totalColorCount: '1',
                productCurSlotPrice: null,
                productOrgSlotPrice: '$40 - $44',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'MSX by Michael Strahan 2-pk. Cotton Stretch V-Neck T-Shirts - Big & Tall',
                imageId: 'DP0302201717084509M.tif',
                productUrl: '/p/msx-by-michael-strahan-2-pk-cotton-stretch-v-neck-t-shirts-big-tall/ppr5007161198?pTmplType=regular&searchTerm=shirts big&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: null,
                productOrgSlotPrice: '$40',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'MSX by Michael Strahan 2-pk. Cotton Stretch Crewneck T-Shirts - Big & Tall',
                imageId: 'DP0302201717084498M.tif',
                productUrl: '/p/msx-by-michael-strahan-2-pk-cotton-stretch-crewneck-t-shirts-big-tall/ppr5007161191?pTmplType=regular&searchTerm=shirts big&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: null,
                productOrgSlotPrice: '$40',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with flowers',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
    {
        term: 'shirts with last',
        url: '/s/shirts-with-flowers?searchType=Predictive+Search&Ntt=shirts+with+flowers&predSearchTerm=shirts',
        products: [
            {
                title: 'Arizona Short Sleeve Pattern Button-Front Shirt',
                imageId: 'DP0511201701132235M.tif',
                productUrl: '/p/arizona-short-sleeve-pattern-button-front-shirt/ppr5007146059?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|1',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '3',
                productCurSlotPrice: '$14.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Slay All Day\' Graphic T-Shirt- Juniors',
                imageId: 'DP0613201717142815M.tif',
                productUrl: '/p/slay-all-day-graphic-t-shirt-juniors/ppr5007231504?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|2',
                averageRating: '5.0',
                totalReviewCount: '1',
                totalColorCount: '1',
                productCurSlotPrice: '$12.99 sale',
                productOrgSlotPrice: '$24 original',
                productPromoMktgLabel: null,
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
            {
                title: 'Alfred Dunner Blue Lagoon Eyelet Lace Flower Shells Petites',
                imageId: 'DP0502201705202842M.tif',
                productUrl: '/p/alfred-dunner-blue-lagoon-eyelet-lace-flower-shells-petites/ppr5007208472?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|3',
                averageRating: '0.0',
                totalReviewCount: '0',
                totalColorCount: '1',
                productCurSlotPrice: 'null',
                productOrgSlotPrice: '$54',
                productPromoMktgLabel: 'BUY 1 GET 1 50% OFF',
                productMapPriceDesc: null,
                productPromoMessage: null,
            },
            {
                title: 'Rewind Short Sleeve Round Neck Floral T-Shirt-Womens Juniors',
                imageId: 'DP0410201717301734M.tif',
                productUrl: '/p/rewind-short-sleeve-round-neck-floral-t-shirt-womens-juniors/ppr5007232780?pTmplType=regular&searchTerm=shirts with flowers&catId=SearchResults&searchType=Predictive%20Search|Products|4',
                averageRating: '4.5',
                totalReviewCount: '14',
                totalColorCount: '5',
                productCurSlotPrice: '$19.99 sale',
                productOrgSlotPrice: '$34 original',
                productPromoMktgLabel: 'null',
                productMapPriceDesc: null,
                productPromoMessage: 'null',
            },
        ],
    },
];
