const StoreMockData = {
    stores: [
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
            ],
            id: '2055',
            name: 'Collin Creek Mall',
            street: '821 N Central Expwy',
            city: 'Plano',
            zip: '75075',
            phone: '(972) 578-8666',
            distance: 7.1,
            latitude: 33.01284,
            longitude: -96.71364,
            number: '2055',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '11:00am-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'wedding registry',
                'optical',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
            ],
            id: '2982',
            name: 'Village @ Fairview',
            street: '301 Stacy Rd',
            city: 'Fairview',
            zip: '75069',
            phone: '(972) 549-4094',
            distance: 10.0,
            latitude: 33.13107,
            longitude: -96.64784,
            number: '2982',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'furniture',
                'wedding registry',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041601',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Un available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
            ],
            id: '2982',
            name: 'Hillage @ Bairview',
            street: '3011 Hacy Rd',
            city: 'Fairview',
            zip: '75069',
            phone: '(972) 549-4194',
            distance: 10.0,
            latitude: 33.13188,
            longitude: -96.64784,
            number: '2982',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'furniture',
                'wedding registry',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
            ],
            id: '2410',
            name: 'Vista Ridge Mall',
            street: '2401 S Stemmons Fwy  Ste 4000',
            city: 'Lewisville',
            zip: '75067',
            phone: '(972) 315-3900',
            distance: 10.8,
            latitude: 33.00318,
            longitude: -96.97244,
            number: '2410',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '11:00am-6:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'wedding registry',
                'optical',
                'portrait studio',
                'salon',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
            ],
            id: '0179',
            name: 'Timber Creek Crossng',
            street: '6051 Skillman St',
            city: 'Dallas',
            zip: '75231',
            phone: '(972) 892-2050',
            distance: 15.3,
            latitude: 32.86288,
            longitude: -96.75233,
            number: '0179',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: 'Special Holiday Hours<p>Mon 6:00am-10:00pm</p><p>Tue-Fri 10:00am-9:00pm</p><p>Sat 10:00am-8:00pm</p><p>Sun 11:00am-8:00pm</p><p>(Note) Except where prohibited by law</p>',
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'wedding registry',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '2921',
            name: 'Robertsons Creek',
            street: '5751 Long Prairie Rd',
            city: 'Flower Mound',
            zip: '75028',
            phone: '(972) 874-6725',
            distance: 15.8,
            latitude: 33.063526,
            longitude: -97.081245,
            number: '2921',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '1046',
            name: 'Golden Triangle Mall',
            street: '2201 S Interstate 35 E Ste D',
            city: 'Denton',
            zip: '76205',
            phone: '(940) 566-6086',
            distance: 18.9,
            latitude: 33.18941,
            longitude: -97.10759,
            number: '1046',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-6:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'custom decorating',
                'optical',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '2338',
            name: 'Town East Mall',
            street: '6000 Town East Mall',
            city: 'Mesquite',
            zip: '75150',
            phone: '(972) 279-4100',
            distance: 21.7,
            latitude: 32.80629,
            longitude: -96.62279,
            number: '2338',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '11:00am-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'furniture',
                'wedding registry',
                'optical',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [],
            id: '2946',
            name: 'Plaza @ Rockwall',
            street: '1015 E I 30',
            city: 'Rockwall',
            zip: '75087',
            phone: '(972) 961-9239',
            distance: 24.0,
            latitude: 32.90295,
            longitude: -96.450874,
            number: '2946',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'wedding registry',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '1943',
            name: 'North East Mall',
            street: '1105 Melbourne Dr',
            city: 'Hurst',
            zip: '76053',
            phone: '(817) 284-4761',
            distance: 28.4,
            latitude: 32.83196,
            longitude: -97.19947,
            number: '1943',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '11:00am-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'furniture',
                'wedding registry',
                'optical',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '2905',
            name: 'Alliance Town Ctr',
            street: '3001 Texas Sage Trl',
            city: 'Fort Worth',
            zip: '76177',
            phone: '(817) 745-4800',
            distance: 31.4,
            latitude: 32.913418,
            longitude: -97.312805,
            number: '2905',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Thu',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Fri-Sat',
                    time: '10:00am-10:00pm',
                },
                {
                    days: 'Sun',
                    time: '11:00am-8:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'wedding registry',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
            ],
            id: '2685',
            name: 'The Parks Mall',
            street: '3851 S Cooper St',
            city: 'Arlington',
            zip: '76015',
            phone: '(817) 557-9292',
            distance: 33.2,
            latitude: 32.68068,
            longitude: -97.12822,
            number: '2685',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-6:00pm',
                },
            ],
            timingsOverrideMessage: 'Special Holiday Hours<p>Mon 6:00am-10:00pm</p><p>Tue-Fri 10:00am-9:00pm</p><p>Sat 10:00am-8:00pm</p><p>Sun 11:00am-8:00pm</p><p>(Note) Except where prohibited by law</p>',
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'wedding registry',
                'optical',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
            ],
            id: '2826',
            name: 'Cedar Hill Vlg',
            street: '333 N Hwy 67',
            city: 'Cedar Hill',
            zip: '75104',
            phone: '(972) 293-0273',
            distance: 34.4,
            latitude: 32.59359,
            longitude: -96.94627,
            number: '2826',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: 'Special Holiday Hours<p>Mon 6:00am-10:00pm</p><p>Tue-Fri 10:00am-9:00pm</p><p>Sat 10:00am-8:00pm</p><p>Sun 11:00am-8:00pm</p><p>(Note) Except where prohibited by law</p>',
            services: [
                'big and tall',
                'major appliances',
                'wedding registry',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '2105',
            name: 'Crossroads Mall',
            street: '6834 Wesley St Ste C',
            city: 'Greenville',
            zip: '75402',
            phone: '(903) 455-5252',
            distance: 40.4,
            latitude: 33.10209,
            longitude: -96.11124,
            number: '2105',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '1:00pm-6:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'salon',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '2969',
            name: 'Sherman Town Ctr',
            street: '610 Graham Dr',
            city: 'Sherman',
            zip: '75092',
            phone: '(903) 870-0489',
            distance: 43.3,
            latitude: 33.68385,
            longitude: -96.61221,
            number: '2969',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'wedding registry',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
            ],
            id: '1419',
            name: 'Ridgmar Mall',
            street: '1900 Green Oaks Rd',
            city: 'Fort Worth',
            zip: '76116',
            phone: '(817) 731-6371',
            distance: 43.3,
            latitude: 32.74065,
            longitude: -97.43793,
            number: '1419',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-6:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'custom decorating',
                'furniture',
                'wedding registry',
                'optical',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '2949',
            name: 'Waxahachie Crossing',
            street: '1441 N Hwy 77',
            city: 'Waxahachie',
            zip: '75165',
            phone: '(972) 937-3042',
            distance: 45.2,
            latitude: 32.42511,
            longitude: -96.84112,
            number: '2949',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'wedding registry',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '2017-04-06T20:02:14.440-0500',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
            ],
            id: '2838',
            name: 'Burleson Town Ctr',
            street: '877 NE Alsbury Blvd',
            city: 'Burleson',
            zip: '76028',
            phone: '(817) 295-0638',
            distance: 46.2,
            latitude: 32.56572,
            longitude: -97.32074,
            number: '2838',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'major appliances',
                'wedding registry',
                'portrait studio',
                'salon',
                'Sephora',
                'jewelry',
            ],
        },
        {
            items: [
                {
                    id: 'ci60691041602',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1021201617053000M.tif',
                    },
                },
                {
                    id: 'ci60691042297',
                    skuId: null,
                    inventory: {
                        status: 'INSTOCK',
                        message: 'In Stock',
                        pickUpStatus: 'AVAILABLE',
                        pickUpMessage: 'Available for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1028201617425276M.tif',
                    },
                },
                {
                    id: 'ci60691042294',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP1209201617125505M.tif',
                    },
                },
                {
                    id: 'ci60691042888',
                    skuId: null,
                    inventory: {
                        status: 'NOTAVAILABLE',
                        message: 'Not Available',
                        pickUpStatus: 'UNAVAILABLE',
                        pickUpMessage: 'Unavailable for Same-Day Pickup',
                        pickUpQuantity: 1,
                        updatedAsOf: '1969-12-31T18:00:00.000-0600',
                        imageURL: '//s7d9.scene7.com/is/image/JCPenney/DP0812201620312913C.tif',
                    },
                },
            ],
            id: '2962',
            name: 'Weatherford Ridge',
            street: '725 Adams Dr',
            city: 'Weatherford',
            zip: '76086',
            phone: '(817) 594-3440',
            distance: 61.4,
            latitude: 32.73315,
            longitude: -97.784096,
            number: '2962',
            country: null,
            state: 'TX',
            timings: [
                {
                    days: 'Mon-Sat',
                    time: '10:00am-9:00pm',
                },
                {
                    days: 'Sun',
                    time: '12:00pm-7:00pm',
                },
            ],
            timingsOverrideMessage: null,
            services: [
                'big and tall',
                'salon',
                'jewelry',
            ],
        },
    ],
};

export default StoreMockData;
