export default {
    status: 200,
    numCoupons: 13,
    data: [
        {
            _meta: {
                id: 'cf99223e-ca88-44e5-84fe-30d395f58e32',
                type: 'content',
                contentType: 'couponTile',
                name: 'week_26_07.26_-_07.29_BUYNOW37',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 15,
                publishingStartDate: '2017-07-26T00:00:00.000-05:00',
                publishingEndDate: '2017-07-29T00:59:59.000-05:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'SSTEPH11',
            },
            offerStartDate: '2017-07-26T00:00:00-05:00',
            redeemingChannel: 'online',
            linkText: 'shop sales',
            disclaimerTemplate: '\'*ONLINE ONLY: $10 off select apparel, shoes, accessories, fine jewelry and home purchases of $25 or more. Extra 30% off select apparel, shoes, accessories, fine jewelry and home purchases. Extra 15% off select furniture, mattresses, custom blinds and shades purchases. Extra 10% off select watches and salon products. Each offer good at jcp.com only, excluding taxes and shipping charges, 7/26/17-7/29/17. IN STORE ONLY: $10 off select apparel, shoes, accessories, fine jewelry and home purchases of $25 or more. Extra 15% off select furniture, mattresses, custom blinds and shades purchases. Extra 10% off select watches and salon products. Each offer good in store only, excluding taxes and shipping charges, 7/26/17-7/29/17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons.\n\nDoes not apply to Best Value, Levi\'s, Disney Collection, Disney Tsum Tsum, Fisher-Price, Licensed Team Sports Merchandise, Columbia, Nike, adidas, Converse, Clarks, Athletic Shoes, Goddess Lingerie, Jewelry Trunk Shows, Modern Bride Diamond Vault, Pre-Owned Watches, Garmin, Sephora, Food, Penney Lane, Electrics/Electronics, Appliances, Hunter Douglas, Tempur-Pedic, Floor Care, Toys, Baby Furniture, Baby Gear, Personalized Jewelry, Wigs and Extensions, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Furniture Outlet purchases, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. $ off savings applied to all qualifying items on prorated basis; any refunds will be given in the prorated amount. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.\n\nINSTRUCTIONS FOR JCP.COM ORDERS: $ off and extra % off offers cannot be applied on the same order.For $ off, enter the online code DEALS47 when prompted at checkout. For extra % off, enter the online code BUYNOW37 when prompted at checkout. Or call 1.800.322.1189 and mention the code.\'\n',
            linkUrl: '/g/sales-deals/N-1b0cnoo?pageType=X2H2&cm_re=CPN-_-0726-_-BUYNOW37-OL_SS',
            linkAppUrl: '/g/sales-deals/N-1b0cnoo?pageType=X2H2&cm_re=CPN-_-0726-_-BUYNOW37-OL_SS',
            promoCode: 'DPDRPOUN',
            offerEndDate: '2017-07-29T00:59:59-05:00',
            disclaimer: '\'*ONLINE ONLY: $10 off select apparel, shoes, accessories, fine jewelry and home purchases of $25 or more. Extra 30% off select apparel, shoes, accessories, fine jewelry and home purchases. Extra 15% off select furniture, mattresses, custom blinds and shades purchases. Extra 10% off select watches and salon products. Each offer good at jcp.com only, excluding taxes and shipping charges, 7/26/17-7/29/17. IN STORE ONLY: $10 off select apparel, shoes, accessories, fine jewelry and home purchases of $25 or more. Extra 15% off select furniture, mattresses, custom blinds and shades purchases. Extra 10% off select watches and salon products. Each offer good in store only, excluding taxes and shipping charges, 7/26/17-7/29/17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons.\n\nDoes not apply to Best Value, Levi\'s, Disney Collection, Disney Tsum Tsum, Fisher-Price, Licensed Team Sports Merchandise, Columbia, Nike, adidas, Converse, Clarks, Athletic Shoes, Goddess Lingerie, Jewelry Trunk Shows, Modern Bride Diamond Vault, Pre-Owned Watches, Garmin, Sephora, Food, Penney Lane, Electrics/Electronics, Appliances, Hunter Douglas, Tempur-Pedic, Floor Care, Toys, Baby Furniture, Baby Gear, Personalized Jewelry, Wigs and Extensions, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Furniture Outlet purchases, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. $ off savings applied to all qualifying items on prorated basis; any refunds will be given in the prorated amount. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.\n\nINSTRUCTIONS FOR JCP.COM ORDERS: $ off and extra % off offers cannot be applied on the same order.For $ off, enter the online code DEALS47 when prompted at checkout. For extra % off, enter the online code BUYNOW37 when prompted at checkout. Or call 1.800.322.1189 and mention the code.\'\n',
            offers: [
                {
                    bodyCopy: 'select apparel, shoes, accessories, fine jewelry & home',
                    headLine: 'EXTRA 30% OFF',
                },
            ],
        },
        {
            _meta: {
                id: '4a59815b-9f15-4a18-9a7f-68643c7f61b7',
                type: 'content',
                contentType: 'couponTile',
                name: 'week_26_07.26_-_07.29_DEALS47',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 15,
                publishingStartDate: '2017-07-26T00:00:00.000-05:00',
                publishingEndDate: '2017-07-29T23:59:59.000-05:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'SSTEPH11',
            },
            disclaimerTemplate: '\'*ONLINE ONLY: $10 off select apparel, shoes, accessories, fine jewelry and home purchases of $25 or more. Extra 30% off select apparel, shoes, accessories, fine jewelry and home purchases. Extra 15% off select furniture, mattresses, custom blinds and shades purchases. Extra 10% off select watches and salon products. Each offer good at jcp.com only, excluding taxes and shipping charges, 7/26/17-7/29/17. IN STORE ONLY: $10 off select apparel, shoes, accessories, fine jewelry and home purchases of $25 or more. Extra 15% off select furniture, mattresses, custom blinds and shades purchases. Extra 10% off select watches and salon products. Each offer good in store only, excluding taxes and shipping charges, 7/26/17-7/29/17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons.\n\nDoes not apply to Best Value, Levi\'s, Disney Collection, Disney Tsum Tsum, Fisher-Price, Licensed Team Sports Merchandise, Columbia, Nike, adidas, Converse, Clarks, Athletic Shoes, Goddess Lingerie, Jewelry Trunk Shows, Modern Bride Diamond Vault, Pre-Owned Watches, Garmin, Sephora, Food, Penney Lane, Electrics/Electronics, Appliances, Hunter Douglas, Tempur-Pedic, Floor Care, Toys, Baby Furniture, Baby Gear, Personalized Jewelry, Wigs and Extensions, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Furniture Outlet purchases, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. $ off savings applied to all qualifying items on prorated basis; any refunds will be given in the prorated amount. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.\n\nINSTRUCTIONS FOR JCP.COM ORDERS: $ off and extra % off offers cannot be applied on the same order.For $ off, enter the online code DEALS47 when prompted at checkout. For extra % off, enter the online code BUYNOW37 when prompted at checkout. Or call 1.800.322.1189 and mention the code.\'\n',
            barCodeUrl: 'https://e.jcpenney.com/pub/sf/ResponseForm?_ri_=X0Gzc2X%3DWQpglLjHJlYQGonBTszddwrH7IWc2kbzdzf3l4HBdMLVXMtX%3DWQpglLjHJlYQGtYzbDzbriaiBIiW6X7esRBYjONo63&_ei_=Et9LBVWUbl-97dmQlurKCp4',
            offerStartDate: '2017-07-26T00:00:00-05:00',
            linkUrl: '/g/sales-deals/N-1b0cnoo?pageType=X2H2&cm_re=CPN-_-0726-_-DEALS47-OL_SS',
            redeemingChannel: 'all',
            linkAppUrl: '/g/sales-deals/N-1b0cnoo?pageType=X2H2&cm_re=CPN-_-0726-_-DEALS47-OL_SS',
            promoCode: 'COUPON',
            linkText: 'shop sales',
            offerEndDate: '2017-07-29T23:59:59-05:00',
            disclaimer: '\'*ONLINE ONLY: $10 off select apparel, shoes, accessories, fine jewelry and home purchases of $25 or more. Extra 30% off select apparel, shoes, accessories, fine jewelry and home purchases. Extra 15% off select furniture, mattresses, custom blinds and shades purchases. Extra 10% off select watches and salon products. Each offer good at jcp.com only, excluding taxes and shipping charges, 7/26/17-7/29/17. IN STORE ONLY: $10 off select apparel, shoes, accessories, fine jewelry and home purchases of $25 or more. Extra 15% off select furniture, mattresses, custom blinds and shades purchases. Extra 10% off select watches and salon products. Each offer good in store only, excluding taxes and shipping charges, 7/26/17-7/29/17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons.\n\nDoes not apply to Best Value, Levi\'s, Disney Collection, Disney Tsum Tsum, Fisher-Price, Licensed Team Sports Merchandise, Columbia, Nike, adidas, Converse, Clarks, Athletic Shoes, Goddess Lingerie, Jewelry Trunk Shows, Modern Bride Diamond Vault, Pre-Owned Watches, Garmin, Sephora, Food, Penney Lane, Electrics/Electronics, Appliances, Hunter Douglas, Tempur-Pedic, Floor Care, Toys, Baby Furniture, Baby Gear, Personalized Jewelry, Wigs and Extensions, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Furniture Outlet purchases, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. $ off savings applied to all qualifying items on prorated basis; any refunds will be given in the prorated amount. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.\n\nINSTRUCTIONS FOR JCP.COM ORDERS: $ off and extra % off offers cannot be applied on the same order.For $ off, enter the online code DEALS47 when prompted at checkout. For extra % off, enter the online code BUYNOW37 when prompted at checkout. Or call 1.800.322.1189 and mention the code.\'\n',
            offers: [
                {
                    bodyCopy: 'select apparel, shoes, accessories, fine jewelry & home',
                    headLine: '$10 OFF $25 ',
                    barCode: 'MC4562100002000000095210',
                },
            ],
        },
        {
            _meta: {
                id: '0c08abb8-5e37-4668-bbaf-25621972bfe4',
                type: 'content',
                contentType: 'couponTile',
                name: 'week_25_07.19_-_08.05_FRIDGE7',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 10,
                publishingStartDate: '2017-07-19T00:00:00.000-05:00',
                publishingEndDate: '2017-08-05T23:59:59.000-05:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'SSTEPH11',
            },
            disclaimerTemplate: '\' *Extra 10% off select major appliance purchases. Offer good at jcp.com only, excluding taxes and shipping charges, 7/19/17-8/5/17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons. \n\nDoes not apply to Best Value, Electrics/Electronics, Limited Time Specials, Purchase with Purchase Items, Home Services, Service Plans, Gift Cards, current orders and prior purchases, or in combination with other coupon(s). Can be combined with earned JCPenney Rewards. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior. REPRODUCTIONS WILL NOT BE ACCEPTED. \n\nINSTRUCTIONS FOR JCP.COM ORDERS: Enter online code FRIDGE7 when prompted at checkout or call 1.800.322.1189 and mention the code.  \'\n',
            offerStartDate: '2017-07-19T00:00:00-05:00',
            linkUrl: '/g/appliances/N-1b2ke21?pageType=X2H2&cm_re=CPN-_-0719-_-FRIDGE7-OL_SS',
            redeemingChannel: 'online',
            linkAppUrl: '/g/appliances/N-1b2ke21?pageType=X2H2&cm_re=CPN-_-0719-_-FRIDGE7-OL_SS',
            promoCode: 'FRIDGE7',
            linkText: 'shop major appliances',
            offerEndDate: '2017-08-05T23:59:59-05:00',
            disclaimer: '\' *Extra 10% off select major appliance purchases. Offer good at jcp.com only, excluding taxes and shipping charges, 7/19/17-8/5/17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons. \n\nDoes not apply to Best Value, Electrics/Electronics, Limited Time Specials, Purchase with Purchase Items, Home Services, Service Plans, Gift Cards, current orders and prior purchases, or in combination with other coupon(s). Can be combined with earned JCPenney Rewards. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior. REPRODUCTIONS WILL NOT BE ACCEPTED. \n\nINSTRUCTIONS FOR JCP.COM ORDERS: Enter online code FRIDGE7 when prompted at checkout or call 1.800.322.1189 and mention the code.  \'\n',
            offers: [
                {
                    bodyCopy: 'select major appliances',
                    headLine: 'HOME - EXTRA 10% OFF',
                },
            ],
        },
        {
            _meta: {
                id: '02a95b53-e373-4ad8-af3d-30ba92d02a35',
                type: 'content',
                contentType: 'couponTile',
                name: 'week_25_07.21_-_08.08_26JEWELS',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 10,
                publishingStartDate: '2017-07-21T00:00:00.000-05:00',
                publishingEndDate: '2017-08-08T23:59:59.000-05:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'SSTEPH11',
            },
            disclaimerTemplate: '\'*Extra 20% off select fine and fashion jewelry purchases with your JCPenney Credit Card or extra 15% off with any other method of payment. Extra 10% off select watch purchases with any method of payment. Each offer good in store and at jcp.com, excluding taxes and shipping charges, 7/21/17-8/8/17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons. Full amount of purchase must be on the JCPenney Credit Card to get the 20% off discount. Subject to credit approval. \n\nDoes not apply to Best Value, Jewelry Trunk Shows, Modern Bride Diamond Vault, Pre-Owned Watches, Garmin, Personalized Jewelry, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Coupon can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior. REPRODUCTIONS WILL NOT BE ACCEPTED.\n\nINSTRUCTIONS FOR JCP.COM ORDERS: Enter online code 26JEWELS when prompted at checkout or call 1.800.322.1189 and mention the code.\'\n',
            barCodeUrl: 'https://e.jcpenney.com/pub/sf/ResponseForm?_ri_=X0Gzc2X%3DWQpglLjHJlYQGmd8pzezbsDizees2zbDSzgzbJIrH7bBhfVXMtX%3DWQpglLjHJlYQGl0Pzbzfpi4zcB6Kzfzc8UFetfSuFzaHWC&_ei_=EjQkBbJAn2TipjR-UZhpSJA',
            offerStartDate: '2017-07-21T00:00:00-05:00',
            linkUrl: '/g/jewelry-and-watches/N-bwo44?pageType=X2H2&cm_re=CPN-_-0721-_-26JEWELS-STR-OL_SJ',
            redeemingChannel: 'all',
            linkAppUrl: '/g/jewelry-and-watches/N-bwo44?pageType=X2H2&cm_re=CPN-_-0721-_-26JEWELS-STR-OL_SJ',
            promoCode: '26JEWELS',
            linkText: 'shop jewelry',
            offerEndDate: '2017-08-08T23:59:59-05:00',
            disclaimer: '\'*Extra 20% off select fine and fashion jewelry purchases with your JCPenney Credit Card or extra 15% off with any other method of payment. Extra 10% off select watch purchases with any method of payment. Each offer good in store and at jcp.com, excluding taxes and shipping charges, 7/21/17-8/8/17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons. Full amount of purchase must be on the JCPenney Credit Card to get the 20% off discount. Subject to credit approval. \n\nDoes not apply to Best Value, Jewelry Trunk Shows, Modern Bride Diamond Vault, Pre-Owned Watches, Garmin, Personalized Jewelry, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Coupon can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior. REPRODUCTIONS WILL NOT BE ACCEPTED.\n\nINSTRUCTIONS FOR JCP.COM ORDERS: Enter online code 26JEWELS when prompted at checkout or call 1.800.322.1189 and mention the code.\'\n',
            offers: [
                {
                    bodyCopy: 'with your jcpenney credit card',
                    headLine: 'JEWELRY - EXTRA 20% OFF',
                    barCode: 'MC4561660003000000595120',
                },
                {
                    bodyCopy: 'with any method of payment',
                    headLine: 'EXTRA 15% OFF',
                    barCode: 'MC4561650003000000595115',
                },
            ],
        },
        {
            _meta: {
                id: 'c78e6806-a428-4960-a476-726325f6f67a',
                type: 'content',
                contentType: 'couponTile',
                name: 'week_25_07.21_-_08.08_26HOME',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 10,
                publishingStartDate: '2017-07-21T00:00:00.000-05:00',
                publishingEndDate: '2017-08-08T23:59:59.000-05:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'SSTEPH11',
            },
            disclaimerTemplate: '\'*Extra 20% off select home purchases with your JCPenney Credit Card or extra 15% off with any other method of payment. Extra 15% off select furniture, mattresses, custom blinds and shades purchases with any method of payment. Each offer good in store and at jcp.com, excluding taxes and shipping charges, 7/21/17-8/8/17. One use per coupon,one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons. Full amount of purchase must be on the JCPenney Credit Card to get the 20% off discount. Subject to credit approval. \n\nDoes not apply to Best Value, Levi\'s, Nike, Columbia, Fisher-Price, Food, Penney Lane, Electrics/Electronics, Appliances, Hunter Douglas, Tempur-Pedic, Floor Care, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Furniture Outlet purchases, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Coupon can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.\n\nINSTRUCTIONS FOR JCP.COM ORDERS: Enter online code 26HOME when prompted at checkout or call 1.800.322.1189 and mention the code. \'',
            barCodeUrl: 'https://e.jcpenney.com/pub/sf/ResponseForm?_ri_=X0Gzc2X%3DWQpglLjHJlYQGNWAcwIBMGjcIBnDizeU7zczb7aGXlWVXMtX%3DWQpglLjHJlYQGg99AP1nM8M3SSDvJYIfLlGGzaHAzg&_ei_=El14TVRx8agh3AXl6BwKJgI',
            offerStartDate: '2017-07-21T00:00:00-05:00',
            linkUrl: '/g/home-store/N-bwo3v?pageType=X2H2&cm_re=CPN-_-0721-_-26HOME-STR-OL_SS',
            redeemingChannel: 'all',
            linkAppUrl: '/g/home-store/N-bwo3v?pageType=X2H2&cm_re=CPN-_-0721-_-26HOME-STR-OL_SS',
            promoCode: '26HOME',
            linkText: 'shop home',
            offerEndDate: '2017-08-08T23:59:59-05:00',
            disclaimer: '\'*Extra 20% off select home purchases with your JCPenney Credit Card or extra 15% off with any other method of payment. Extra 15% off select furniture, mattresses, custom blinds and shades purchases with any method of payment. Each offer good in store and at jcp.com, excluding taxes and shipping charges, 7/21/17-8/8/17. One use per coupon,one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons. Full amount of purchase must be on the JCPenney Credit Card to get the 20% off discount. Subject to credit approval. \n\nDoes not apply to Best Value, Levi\'s, Nike, Columbia, Fisher-Price, Food, Penney Lane, Electrics/Electronics, Appliances, Hunter Douglas, Tempur-Pedic, Floor Care, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Furniture Outlet purchases, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Coupon can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.\n\nINSTRUCTIONS FOR JCP.COM ORDERS: Enter online code 26HOME when prompted at checkout or call 1.800.322.1189 and mention the code. \'',
            offers: [
                {
                    bodyCopy: 'with your jcpenney credit card',
                    headLine: 'HOME - EXTRA 20% OFF',
                    barCode: 'MC4561630003000000495120',
                },
                {
                    bodyCopy: 'with any method of payment',
                    headLine: 'EXTRA 15% OFF',
                    barCode: 'MC4561620003000000495115',
                },
            ],
        },
        {
            _meta: {
                id: '0421eae8-5275-41e1-bfc0-9ef4bd3a0505',
                type: 'content',
                contentType: 'couponTile',
                name: 'SCHOOL2_ends_9.10',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 10,
                publishingStartDate: '2017-06-29T00:00:00.000-05:00',
                publishingEndDate: '2017-09-10T23:59:59.000-05:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'NCHINTHI',
            },
            disclaimerTemplate: '\'*$10 off select kids\' apparel and accessories purchases of $50 or more.Offer good in store and at jcp.com, excluding taxes and shipping charges, 6/1/17- 9 / 10 / 17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Does not apply to Best Value, Levi\'s, Disney Collection, Licensed Team Sports Merchandise, Columbia, Nike, adidas, Toys, Baby Gear, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. $ off savings applied to all qualifying items on prorated basis; any refunds will be given in the prorated amount. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.INSTRUCTIONS FOR JCP.COM ORDERS: Enter online code SCHOOL2 when prompted at checkout or call 1.800.322.1189 and mention code.\' ',
            offerStartDate: '2017-06-29T00:00:00-05:00',
            barCodeUrl: 'https://e.jcpenney.com/pub/sf/ResponseForm?_ri_=X0Gzc2X%3DWQpglLjHJlYQGNza74OzazeonrN9nK94NzaLzawRzezdsdzeVXMtX%3DWQpglLjHJlYQGoNS7wzdbpG63XOzaSHtfq4MX0cFdX&amp;_ei_=Ep_afEHCxrZPNfQsUxylm6I',
            linkUrl: '/g/school-uniforms/N-bwo40D1nox9p?cm_re=CPN-_-0601-_-SCHOOL2-STR-OL_SS',
            redeemingChannel: 'all',
            linkText: 'SHOP KIDS',
            promoCode: 'SCHOOL2',
            offerEndDate: '2017-09-10T23:59:59-05:00',
            disclaimer: '\'*$10 off select kids\' apparel and accessories purchases of $50 or more.Offer good in store and at jcp.com, excluding taxes and shipping charges, 6/1/17- 9 / 10 / 17. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Does not apply to Best Value, Levi\'s, Disney Collection, Licensed Team Sports Merchandise, Columbia, Nike, adidas, Toys, Baby Gear, Limited Time Specials, Purchase with Purchase Items, In-Store Services, Home Services, Service Plans, Gift Cards, Closing Store purchases, current orders and prior purchases, or in combination with other coupon(s). Can be combined with earned JCPenney Rewards and JCPenney Credit Card new account in-store discount. Coupon cannot be used for payment on account. Coupon cannot be redeemed as cash or merchandise credit if merchandise is returned. $ off savings applied to all qualifying items on prorated basis; any refunds will be given in the prorated amount. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.INSTRUCTIONS FOR JCP.COM ORDERS: Enter online code SCHOOL2 when prompted at checkout or call 1.800.322.1189 and mention code.\' ',
            offers: [
                {
                    bodyCopy: 'select kids\' apparel & accessories',
                    headLine: 'KIDS - $10 OFF $50',
                    barCode: 'MC4558750003000000316210',
                },
            ],
        },
        {
            _meta: {
                id: '6793792b-ddf7-42d2-8aee-3701376d388f',
                type: 'content',
                contentType: 'couponTile',
                name: 'week_25_07.20_TO_8.19_Free_Shipping_to_Stores',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 10,
                publishingStartDate: '2017-07-20T00:00:00.000-05:00',
                publishingEndDate: '2017-12-31T23:59:59.000-06:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'SSTEPH11',
            },
            disclaimerTemplate: '\'FREE SHIPPING TO STORES NO MINIMUM\nApplies to free shipping to JCPenney store (4-7 business days) with no minimum purchase. You will be contacted when your order arrives in store. Free shipping excludes truck delivered items and select manufacturer shipped items.\'\n',
            offerStartDate: '2017-07-20T00:00:00-05:00',
            linkUrl: '/g/sales-deals/N-1b0cnoo?pageType=X2H2&cm_re=CPN-_-0720-_-FSTS_SS',
            redeemingChannel: 'all',
            linkAppUrl: '/g/sales-deals/N-1b0cnoo?pageType=X2H2&cm_re=CPN-_-0720-_-FSTS_SS',
            linkText: 'shop now',
            offerEndDate: '2017-12-31T23:59:59-06:00',
            disclaimer: '\'FREE SHIPPING TO STORES NO MINIMUM\nApplies to free shipping to JCPenney store (4-7 business days) with no minimum purchase. You will be contacted when your order arrives in store. Free shipping excludes truck delivered items and select manufacturer shipped items.\'\n',
            offers: [
                {
                    bodyCopy: 'no minimum required',
                    headLine: 'FREE SHIPPING TO STORES',
                },
            ],
        },
        {
            _meta: {
                id: '26b5ca7f-56c4-46ab-84aa-d33df8d4606f',
                type: 'content',
                contentType: 'couponTile',
                name: 'week_24_07.12_-_07.31_portrait',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 5,
                publishingStartDate: '2017-07-14T00:00:00.000-05:00',
                publishingEndDate: '2017-07-31T23:59:59.000-05:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'SSTEPH11',
            },
            offerStartDate: '2017-07-14T00:00:00-05:00',
            redeemingChannel: 'instore',
            linkText: 'print coupon',
            disclaimerTemplate: 'Present at session. $9.99 session fee per subject or FREE with portrait membership. One offer per family, per day. Two free 5x7 prints of the same image included on one traditional sheet. Traditional sheets are unenhanced, 10x13 or smaller. Digital album includes all high-resolution images photographed in your session with a copyright license to use and modify the images. Bordered products and other specialty designs created in the studio are not included on the digital album. Digital album, traditional sheets and discounted photo cards are not discounted further. Percent off not valid on digital images, digital enhancements, CD, media bundle, featured product or portrait memberships. Not valid on session fees, services, merchandise, reorders, prior purchases, online orders, outdoor/on location sessions or with other offers. JCPenney Portraits reserves the right to modify or discontinue this offer at any time without prior notice. No cash value. Valid through 7/31/17.  PC1812231\n',
            linkUrl: 'http://www.jcpportraits.com/content/OP2231',
            linkAppUrl: 'http://www.jcpportraits.com/content/OP2231',
            offerEndDate: '2017-07-31T23:59:59-05:00',
            disclaimer: 'Present at session. $9.99 session fee per subject or FREE with portrait membership. One offer per family, per day. Two free 5x7 prints of the same image included on one traditional sheet. Traditional sheets are unenhanced, 10x13 or smaller. Digital album includes all high-resolution images photographed in your session with a copyright license to use and modify the images. Bordered products and other specialty designs created in the studio are not included on the digital album. Digital album, traditional sheets and discounted photo cards are not discounted further. Percent off not valid on digital images, digital enhancements, CD, media bundle, featured product or portrait memberships. Not valid on session fees, services, merchandise, reorders, prior purchases, online orders, outdoor/on location sessions or with other offers. JCPenney Portraits reserves the right to modify or discontinue this offer at any time without prior notice. No cash value. Valid through 7/31/17.  PC1812231\n',
            offers: [
                {
                    bodyCopy: 'Two Free 5x7 Traditional Prints',
                    headLine: 'JCPenney PORTRAIT',
                },
            ],
        },
        {
            _meta: {
                id: 'e9ec18dc-fa89-40b7-8f56-1b5fde35090a',
                type: 'content',
                contentType: 'couponTile',
                name: 'week_25_07.16_-_09.09_salon',
                parent: '/content/en_US/JCPenney.com/Coupons/Assets/Content',
                priority: 5,
                publishingStartDate: '2017-07-16T00:00:00.000-05:00',
                publishingEndDate: '2017-09-09T23:59:59.000-05:00',
                active: true,
                publishingChannels: [
                    'large',
                    'small',
                    'app',
                ],
                lastModifiedBy: 'SSTEPH11',
            },
            disclaimerTemplate: '*$10 kids\' cuts with designer or senior designer at JCPenney Salon, excluding taxes, valid through 9/9/17.Offer may not be available at all salons. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons. Cannot be combined with any other coupon or discount offer. Coupon cannot be used for payment on account. $ off savings applied to all qualifying items on prorated basis; any refunds will be given in the prorated amount. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.\n',
            barCodeUrl: 'https://e.jcpenney.com/pub/sf/ResponseForm?_ri_=X0Gzc2X%3DWQpglLjHJlYQGN11czcSzgFgyfUyCnMtB3iKzdzbwrFyVXMtX%3DWQpglLjHJlYQGjdLSRj7fMjzc2eg235lD3cSzdSeuO&_ei_=EhYu28R2s4XhWCCIoy_Mg5M',
            offerStartDate: '2017-07-16T00:00:00-05:00',
            linkUrl: '/jsp/storelocator/storeResults.jsp?_requestid=1380294?cm_re=CPN-_-0716-_-SALON_FS',
            redeemingChannel: 'instore',
            linkAppUrl: '/jsp/storelocator/storeResults.jsp?_requestid=1380294?cm_re=CPN-_-0716-_-SALON_FS',
            linkText: 'find a store',
            offerEndDate: '2017-09-09T23:59:59-05:00',
            disclaimer: '*$10 kids\' cuts with designer or senior designer at JCPenney Salon, excluding taxes, valid through 9/9/17.Offer may not be available at all salons. One use per coupon, one coupon per customer; must be provided/surrendered at time of purchase. Dollar-off offers (including JCPenney Rewards) applied prior to companywide percent-off discounts or coupons. Cannot be combined with any other coupon or discount offer. Coupon cannot be used for payment on account. $ off savings applied to all qualifying items on prorated basis; any refunds will be given in the prorated amount. No cash value. JCPenney may refuse, or limit the use of, any coupon and/or return for any reason, including reoccurring disruptive behavior.REPRODUCTIONS WILL NOT BE ACCEPTED.\n',
            offers: [
                {
                    bodyCopy: 'with a designer or sr. designer',
                    headLine: 'SALON - $10 Kids\' Cuts',
                    barCode: 'MC4560680003000000195210',
                },
            ],
        },
    ],
};
