export const findStoresDetails = {
    stores: [
        {
            id: '2982',
            number: '2982',
            name: 'Village @ Fairview',
            street: '301 Stacy Rd',
            city: 'Fairview',
            zip: '75069',
            state: 'TX',
            country: 'USA',
            phone: '972- 549 - 4094',
            distance: 4.1,
            latitude: 33.13107,
            longitude: -96.64784,
            timings: [
                {
                    days: 'Mon- Sat',
                    time: '10:00am- 9:00pm',
                },
                {
                    days: 'Sun',
                    time: '11:00am- 7:00pm',
                },
            ],
            services: [
                'jewelry',
                'big and tall',
                'wedding registry',
                'furniture',
                'custom decorating',
                'major appliances',
                'Sephora',
                'salon',
                'portrait studio',
            ],
            appointments: [
                {
                    name: 'custom decorating',
                    url: '/dotcom/jsp/browse/categoryMeevoAppointment.jsp?service = custom decorating& storeId=2982',
                },
                {
                    name: 'Sephora',
                    url: '/ dotcom / jsp / browse / categoryMeevoAppointment.jsp ? service = Sephora & storeId=2982',
                },
                {
                    name: 'salon',
                    url: '/ dotcom / jsp / browse / categoryMeevoAppointment.jsp ? service = salon & storeId=2982',
                },
            ],
            openDate: '2009- 07 - 24',
            closeDate: '1900- 01 - 01',
            suspendOrderIndicator: false,
            facilityIndicator: 3,
            restrictedItemHeight: 62,
            restrictedItemWidth: 999,
            restrictedItemLength: 999,
            restrictedItemUnited: 9999,
            restrictedItemWeight: 2416,
            serviceIndicator: true,
            type: 'jcpServices',
        },
        {
            id: '2055',
            number: '2055',
            name: 'Collin Creek Mall',
            street: '821 N Central Expwy',
            city: 'Plano',
            zip: '75075',
            state: 'TX',
            country: 'USA',
            phone: '972- 578 - 8666',
            distance: 12.7,
            latitude: 33.01284,
            longitude: -96.71364,
            timings: [
                {
                    days: 'Mon- Sat',
                    time: '10:00am- 9:00pm',
                },
                {
                    days: 'Sun',
                    time: '11:00am- 7:00pm',
                },
            ],
            services: [
                'jewelry',
                'big and tall',
                'wedding registry',
                'custom decorating',
                'major appliances',
                'Sephora',
                'optical',
                'salon',
                'portrait studio',
            ],
            appointments: [
                {
                    name: 'custom decorating',
                    url: '/ dotcom / jsp / browse / categoryMeevoAppointment.jsp ? service = custom decorating& storeId=2055',
                },
                {
                    name: 'Sephora',
                    url: '/ dotcom / jsp / browse / categoryMeevoAppointment.jsp ? service = Sephora & storeId=2055',
                },
                {
                    name: 'salon',
                    url: '/ dotcom / jsp / browse / categoryMeevoAppointment.jsp ? service = salon & storeId=2055',
                },
            ],
            openDate: '1983- 07 - 27',
            closeDate: '1900- 01 - 01',
            suspendOrderIndicator: false,
            facilityIndicator: 3,
            restrictedItemHeight: 62,
            restrictedItemWidth: 999,
            restrictedItemLength: 999,
            restrictedItemUnited: 9999,
            restrictedItemWeight: 2416,
            serviceIndicator: true,
            type: 'jcpServices',
        },
        {
            id: '2795',
            number: '2795',
            name: 'Stonebriar Mall',
            street: '2607 Preston Rd',
            city: 'Frisco',
            zip: '75034',
            state: 'TX',
            country: 'USA',
            phone: '972- 712 - 2707',
            distance: 13.5,
            latitude: 33.09948,
            longitude: -96.80954,
            timings: [
                {
                    days: 'Mon- Sat',
                    time: '10:00am- 9:00pm',
                },
                {
                    days: 'Sun',
                    time: '11:00am- 7:00pm',
                },
            ],
            services: [
                'jewelry',
                'big and tall',
                'wedding registry',
                'furniture',
                'custom decorating',
                'major appliances',
                'Sephora',
                'optical',
                'salon',
                'portrait studio',
            ],
            appointments: [
                {
                    name: 'custom decorating',
                    url: '/ dotcom / jsp / browse / categoryMeevoAppointment.jsp ? service = custom decorating& storeId=2795',
                },
                {
                    name: 'Sephora',
                    url: '/ dotcom / jsp / browse / categoryMeevoAppointment.jsp ? service = Sephora & storeId=2795',
                },
                {
                    name: 'salon',
                    url: '/ dotcom / jsp / browse / categoryMeevoAppointment.jsp ? service = salon & storeId=2795',
                },
            ],
            openDate: '2000- 07 - 06',
            closeDate: '1900- 01 - 01',
            suspendOrderIndicator: false,
            facilityIndicator: 3,
            restrictedItemHeight: 62,
            restrictedItemWidth: 999,
            restrictedItemLength: 999,
            restrictedItemUnited: 9999,
            restrictedItemWeight: 2416,
            serviceIndicator: true,
            type: 'jcpServices',
        },
    ],
    meta: {
        totalStores: 3,
        totalPages: 1,
    },
    page: [
        {
            url: 'https://m-dt-test2.jcpenney.com/v4/stores?page=1&pageSize=5&limit=50&latitude=33.1632842&longitude=-96.5890166&radius=15.0',
            number: 1,
            selected: true,
        },
    ],
};

export const productDetails = [
    {
        id: 'ci59113015396',
        itemId: '12007190083',
        brandName: 'Nike',
        group: [
            {
                address: { id: 'shippingaddress' },
                id: 'shippingid',
            },
        ],
        modelNumber: null,
        categoryId: 'cat100240063',
        departments: [
            'dept20000018',
        ],
        type: 'REGULAR',
        productNumber: '120-0719D',
        fulfillmentOptions: [
            {
                id: 1,
                message: null,
                selected: true,
                status: null,
                quantity: 0,
            },
            {
                id: 2,
                message: 'Not Offered',
                selected: false,
                status: 'notOffered',
                quantity: 0,
            },
            {
                id: 3,
                message: 'Available',
                selected: false,
                status: 'AVAILABLE',
                quantity: 0,
            },
        ],
        productURL: 'https://m.jcpenney.com:443/v2.2/products/ppr5007204794?SIZE_RANGE=Womens&COLOR=Ltirormrdbrz&SIZE=8%201/2&WIDTH=Medium',
        productId: 'ppr5007204794',
        name: 'Nike Md Runner Womens Running Shoes',
        imageURL: 'https://s7d9.scene7.com/is/image/JCPenney/DP0117201717042087M.tif',
        manufacturerAdvertisedPrice: false,
        activePrice: 69.99,
        originalPrice: 75,
        sale: null,
        isClearance: false,
        savings: 5.01,
        quantity: 1,
        totalItemSavings: 5.01,
        totalWithoutDiscount: 75,
        adjustmentsTotal: 0,
        totalSavings: 5.01,
        overSizedItemSurcharge: 0,
        monogramPrice: 0,
        adjustments: [
            {
                id: null,
                code: null,
                serialNumber: null,
                type: null,
                token: null,
                message: 'Nike items do not qualify for FUNDEAL',
                amount: 0,
                description: null,
                ineligibleItems: null,
                subType: null,
            },
        ],
        total: 69.99,
        inventory: null,
        inventoryStatus: 'INSTOCK',
        prices: [
            {
                amount: 75,
                type: 'ORIGINAL',
                label: null,
            },
            {
                amount: 69.99,
                type: 'SALE',
                label: 'ACTIVE',
            },
        ],
        attributes: [
            {
                type: 'COLOR',
                value: 'Ltirormrdbrz',
                name: null,
                vData: false,
            },
            {
                type: 'SIZE',
                value: '8 1/2',
                name: null,
                vData: false,
            },
            {
                type: 'WIDTH',
                value: 'Medium',
                name: null,
                vData: false,
            },
        ],
        parentId: null,
        adjustmentTotal: null,
        marketingLabel: null,
        deliveryDateType: 'estimated',
        estDeliveryMsg: '',
        manufacturerWarranty: null,
        description: null,
        isNew: true,
        isPreOrder: false,
        isTruckDeliveryRequired: false,
        searchTerm: '',
        subTotal: 69.99,
        digital: false,
        childId: null,
        analytics: {
            rrZone: '',
            searchTerm: '',
            categoryId: '',
            departmentId: 'N-bwo42Z6o',
        },
        giftWrappable: true,
        division: '007',
        subdivision: '120',
        entity: '44',
        giftRegistry: null,
        factorForShippingDiscount: true,
        maxQuantity: 99,
        readOnly: false,
        tracking: null,
        tags: null,
        bundleDiscountApplied: false,
        totalPromotions: 0,
        promotions: null,
    },
    {
        id: 'ci59113015393',
        itemId: '60902560042',
        brandName: 'ADIDAS',
        group: null,
        modelNumber: null,
        categoryId: 'cat100250173',
        departments: [
            'dept20000018',
        ],
        type: 'REGULAR',
        productNumber: '609-0256D',
        fulfillmentOptions: [
            {
                id: 1,
                message: null,
                selected: true,
                status: null,
                quantity: 0,
            },
            {
                id: 2,
                message: 'Not Offered',
                selected: false,
                status: 'notOffered',
                quantity: 0,
            },
            {
                id: 3,
                message: 'Available',
                selected: false,
                status: 'AVAILABLE',
                quantity: 0,
            },
        ],
        productURL: 'https://m.jcpenney.com:443/v2.2/products/ppr5007142691?SIZE_RANGE=Mens&COLOR=Dk%20Grey%20Yellow&SIZE=8%201/2&WIDTH=Medium',
        productId: 'ppr5007142691',
        name: 'Adidas Dark Grey Solar Mens Running Shoes',
        imageURL: 'https://s7d9.scene7.com/is/image/JCPenney/DP0912201617550103M.tif',
        manufacturerAdvertisedPrice: false,
        activePrice: 59.99,
        originalPrice: 65,
        sale: null,
        isClearance: false,
        savings: 5.01,
        quantity: 1,
        totalItemSavings: 5.01,
        totalWithoutDiscount: 65,
        adjustmentsTotal: 0,
        totalSavings: 5.01,
        overSizedItemSurcharge: 0,
        monogramPrice: 0,
        adjustments: [
            {
                id: null,
                code: null,
                serialNumber: null,
                type: null,
                token: null,
                message: 'ADIDAS items do not qualify for FUNDEAL',
                amount: 0,
                description: null,
                ineligibleItems: null,
                subType: null,
            },
        ],
        total: 59.99,
        inventory: null,
        inventoryStatus: 'INSTOCK',
        prices: [
            {
                amount: 65,
                type: 'ORIGINAL',
                label: null,
            },
            {
                amount: 59.99,
                type: 'SALE',
                label: 'ACTIVE',
            },
        ],
        attributes: [
            {
                type: 'COLOR',
                value: 'Dk Grey Yellow',
                name: null,
                vData: false,
            },
            {
                type: 'SIZE',
                value: '8 1/2',
                name: null,
                vData: false,
            },
            {
                type: 'WIDTH',
                value: 'Medium',
                name: null,
                vData: false,
            },
        ],
        parentId: null,
        adjustmentTotal: null,
        marketingLabel: null,
        deliveryDateType: 'estimated',
        estDeliveryMsg: '',
        manufacturerWarranty: null,
        description: null,
        isNew: true,
        isPreOrder: false,
        isTruckDeliveryRequired: false,
        searchTerm: '',
        subTotal: 59.99,
        digital: false,
        childId: null,
        analytics: {
            rrZone: '',
            searchTerm: '',
            categoryId: '',
            departmentId: 'N-bwo42',
        },
        giftWrappable: true,
        division: '007',
        subdivision: '609',
        entity: '44',
        giftRegistry: null,
        factorForShippingDiscount: true,
        maxQuantity: 99,
        readOnly: false,
        tracking: null,
        tags: null,
        bundleDiscountApplied: false,
        totalPromotions: 0,
        promotions: null,
    },
    {
        id: 'ci59113015391',
        itemId: '53193900042',
        brandName: 'STAFFORD',
        group: null,
        modelNumber: null,
        categoryId: 'cat100240025',
        departments: [
            'dept20000014',
        ],
        type: 'REGULAR',
        productNumber: '531-9390D',
        fulfillmentOptions: [
            {
                id: 1,
                message: null,
                selected: true,
                status: null,
                quantity: 0,
            },
            {
                id: 2,
                message: 'Not Offered',
                selected: false,
                status: 'notOffered',
                quantity: 0,
            },
            {
                id: 3,
                message: 'Not Offered',
                selected: false,
                status: 'notOffered',
                quantity: 0,
            },
        ],
        productURL: 'https://m.jcpenney.com:443/v2.2/products/pp5006990446?SIZE_RANGE=Big&SLEEVE=34-35&NECK_SIZE=19&COLOR=Worn%20Indigo',
        productId: 'pp5006990446',
        name: 'StaffordÂ® Travel Easy Care Broadcloth Dress Shirt - Big & Tall',
        imageURL: 'https://s7d9.scene7.com/is/image/JCPenney/DP0323201617041510M.tif',
        manufacturerAdvertisedPrice: false,
        activePrice: 26.99,
        originalPrice: 46,
        sale: null,
        isClearance: false,
        savings: 19.01,
        quantity: 1,
        totalItemSavings: 19.01,
        totalWithoutDiscount: 46,
        adjustmentsTotal: 4.05,
        totalSavings: 23.06,
        overSizedItemSurcharge: 0,
        monogramPrice: 0,
        adjustments: [
            {
                id: null,
                code: 'COUPON',
                serialNumber: null,
                type: 'PercentageOff',
                token: null,
                message: null,
                amount: 4.05,
                description: null,
                ineligibleItems: null,
                subType: null,
            },
        ],
        total: 22.94,
        inventory: null,
        inventoryStatus: 'INSTOCK',
        prices: [
            {
                amount: 46,
                type: 'ORIGINAL',
                label: null,
            },
            {
                amount: 26.99,
                type: 'SALE',
                label: 'ACTIVE',
            },
        ],
        attributes: [
            {
                type: 'SIZE RANGE',
                value: 'Big',
                name: null,
                vData: false,
            },
            {
                type: 'SLEEVE',
                value: '34-35',
                name: null,
                vData: false,
            },
            {
                type: 'NECK_SIZE',
                value: '19',
                name: null,
                vData: false,
            },
            {
                type: 'COLOR',
                value: 'Worn Indigo',
                name: null,
                vData: false,
            },
        ],
        parentId: null,
        adjustmentTotal: null,
        marketingLabel: null,
        deliveryDateType: 'estimated',
        estDeliveryMsg: '',
        manufacturerWarranty: null,
        description: null,
        isNew: false,
        isPreOrder: false,
        isTruckDeliveryRequired: false,
        searchTerm: '',
        subTotal: 26.99,
        digital: false,
        childId: null,
        analytics: {
            rrZone: 'HOME_MOBILE',
            searchTerm: '',
            categoryId: 'Product Recommendation|HOME_MOBILE',
            departmentId: '',
        },
        giftWrappable: true,
        division: '002',
        subdivision: '531',
        entity: '23',
        giftRegistry: null,
        factorForShippingDiscount: true,
        maxQuantity: 99,
        readOnly: false,
        tracking: null,
        tags: null,
        bundleDiscountApplied: false,
        totalPromotions: 0,
        promotions: null,
    },
];
