const HotDealsResponse = {
    requestDateTime: 'Fri Jun 30 19:18:58 CDT 2017',
    channelName: 'EXPCOM-API',
    jvmName: 'dtexpte2l2j2_02',
    requestUrl: 'http://origin-apigw-dt-test2-web-l2.jcpenney.com:80/expcom-api/j/homepage?op=HotDeals1&dpAkamaiOverride=1&version=v5',
    maxAge: 0,
    position: 0,
    HotDeals1:
    {
        requestDateTime: 'Mon Aug 14 04:43:03 CDT 2017',
        channelName: 'EXPCOM-WEB',
        jvmName: 'dtexpte4c2j1_02',
        requestUrl: 'http://dt-test4.jcpenney.com:80/expcom/j/homepage/?op=HotDeals4&expHomePage=true',
        maxAge: 1800,
        marketingHeadLine: 'Hot Deals 44444',
        marketingTagLine: 'Appliances HotSellers Picked for you',
        imagePath: 'hotdeals_4_181.png',
        seoUrl: '/g/sale-women/N-bwo3xZ1fe?test=1',
        certonaEnabled: false,
        dimensionId: '20000013, 1850',
        searchTerm: null,
        recordsInfoList: [
            {
                name: 'Liz ClaiborneÂ® Speckle Leaf Shower Curtain',
                marketingSlot: null,
                ppId: 'pp5004951544',
                currentMin: '0',
                currentMax: '0',
                originalMin: '0',
                originalMax: '0',
                priceType: 'everyday price',
                marketingLabel: null,
                url: null,
                reviewCount: '0',
                imageId: 'DP1231201417005544M.tif',
                colorizedImageId: 'DP1231201417005544M.tif',
                averageRating: '0.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Rustic Gears Set of 2 Wall Decor',
                marketingSlot: null,
                ppId: 'pp5003670073',
                currentMin: '440',
                currentMax: '440',
                originalMin: '440',
                originalMax: '440',
                mapPrice: true,
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/rustic-gears-set-of-2-wall-decor/pp5003670073?pTmplType=regular',
                reviewCount: null,
                imageId: 'DP1231201317014938M.tif',
                colorizedImageId: 'DP1231201317014938M.tif',
                averageRating: null,
                currentPriceLabel: null,
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Fendrel Set of 4 Beveled Square Wall Mirrors ',
                marketingSlot: null,
                ppId: 'pp5003670072',
                currentMin: '239',
                currentMax: '239',
                originalMin: '239',
                originalMax: '239',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/fendrel-set-of-4-beveled-square-wall-mirrors/pp5003670072?pTmplType=regular',
                reviewCount: '1',
                imageId: 'DP1231201317014838M.tif',
                colorizedImageId: 'DP1231201317014838M.tif',
                averageRating: '5.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Micayla Large Scrollwork Iron Metal Wall Decor',
                marketingSlot: null,
                ppId: 'pp5003670071',
                currentMin: '194',
                currentMax: '194',
                originalMin: '194',
                originalMax: '194',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/micayla-large-scrollwork-iron-metal-wall-decor/pp5003670071?pTmplType=regular',
                reviewCount: '2',
                imageId: 'DP1231201317014737M.tif',
                colorizedImageId: 'DP1231201317014737M.tif',
                averageRating: '5.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Micayla Set of 2 Metal Wall Decor',
                marketingSlot: null,
                ppId: 'pp5003670070',
                currentMin: '249',
                currentMax: '249',
                originalMin: '249',
                originalMax: '249',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/micayla-set-of-2-metal-wall-decor/pp5003670070',
                reviewCount: '6',
                imageId: 'DP1231201317014637M.tif',
                colorizedImageId: 'DP1231201317014637M.tif',
                averageRating: '4.830000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Silver-Tone Flowers Set of 3 Wall Decor',
                marketingSlot: null,
                ppId: 'pp5003670068',
                currentMin: '259',
                currentMax: '259',
                originalMin: '259',
                originalMax: '259',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/silver-tone-flowers-set-of-3-wall-decor/pp5003670068?pTmplType=regular',
                reviewCount: '0',
                imageId: 'DP1231201317014437M.tif',
                colorizedImageId: 'DP1231201317014437M.tif',
                averageRating: '0.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Silver-Tone Rings Set of 2 Square Wall Mirrors',
                marketingSlot: null,
                ppId: 'pp5003670067',
                currentMin: '259',
                currentMax: '259',
                originalMin: '259',
                originalMax: '259',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/silver-tone-rings-set-of-2-square-wall-mirrors/pp5003670067?pTmplType=regular',
                reviewCount: '0',
                imageId: 'DP1231201317014337M.tif',
                colorizedImageId: 'DP1231201317014337M.tif',
                averageRating: '0.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Artemis Wall Clock',
                marketingSlot: null,
                ppId: 'pp5003640369',
                currentMin: '199',
                currentMax: '199',
                originalMin: '199',
                originalMax: '199',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/artemis-wall-clock/pp5003640369?pTmplType=regular',
                reviewCount: '2',
                imageId: 'DP1231201317013838M.tif',
                colorizedImageId: 'DP1231201317013838M.tif',
                averageRating: '5.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Monarch Set of 3 Pendulum Wall Clocks',
                marketingSlot: null,
                ppId: 'pp5003640368',
                currentMin: '189',
                currentMax: '189',
                originalMin: '189',
                originalMax: '189',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/monarch-set-of-3-pendulum-wall-clocks/pp5003640368?pTmplType=regular',
                reviewCount: '2',
                imageId: 'DP1231201317013737M.tif',
                colorizedImageId: 'DP1231201317013737M.tif',
                averageRating: '3.500000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Chieron Wall Clock',
                marketingSlot: null,
                ppId: 'pp5003640367',
                currentMin: '159',
                currentMax: '159',
                originalMin: '159',
                originalMax: '159',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/chieron-wall-clock/pp5003640367?pTmplType=regular',
                reviewCount: '3',
                imageId: 'DP1231201317013637M.tif',
                colorizedImageId: 'DP1231201317013637M.tif',
                averageRating: '3.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Regency Villa Tesio Wall Clock',
                marketingSlot: null,
                ppId: 'pp5003640365',
                currentMin: '189',
                currentMax: '189',
                originalMin: '189',
                originalMax: '189',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/regency-villa-tesio-wall-clock/pp5003640365?pTmplType=regular',
                reviewCount: '0',
                imageId: 'DP1231201317013437M.tif',
                colorizedImageId: 'DP1231201317013437M.tif',
                averageRating: '0.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
            {
                name: 'Leonardo Wall Clock',
                marketingSlot: null,
                ppId: 'pp5003640363',
                currentMin: '179',
                currentMax: '179',
                originalMin: '179',
                originalMax: '179',
                priceType: 'everyday price',
                marketingLabel: null,
                url: '/p/leonardo-wall-clock/pp5003640363?pTmplType=regular',
                reviewCount: '3',
                imageId: 'DP1231201317013238M.tif',
                colorizedImageId: 'DP1231201317013238M.tif',
                averageRating: '4.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
        ],
        type: 'HotDeals1',
        allDay: false,
        contentExpiry: 'Mon Aug 21 2017 03:29:56 AM',
        title: 'Hot Deals 4',
        shopAllTitle: 'Shop Deals Now',
        hotDealsH1Tag: 'Shop Hot Deals',
        urlType: 'Internal',
        imageAlt: '',
        certonaStrategy: null,
        marketingTagLineColor: '#E9967A',
        backGroundColor: '#F08080',
        analyticsTag: 'cm_re=HP-hotdeals-_-norecs-_-Shop Hot Deals',
        liveText: 'Ends in: ',
        liveTextColor: 'orange',
        timerTextColor: 'blue',
        liveTextBackGroundColor: 'blue',
        timer: 'Thu Sep 21 2017 12:00:00 AM',
        timerEnabled: true,
    },
    seoTitleTags: null,
};

const HotDealsSEOURLResponse = {
    requestDateTime: 'Fri Jun 30 19:18:58 CDT 2017',
    channelName: 'EXPCOM-API',
    jvmName: 'dtexpte2l2j2_02',
    requestUrl: 'http://origin-apigw-dt-test2-web-l2.jcpenney.com:80/expcom-api/j/homepage?op=HotDeals1&dpAkamaiOverride=1&version=v5',
    maxAge: 0,
    position: 0,
    HotDeals1:
    {
        requestDateTime: 'Mon Aug 14 04:43:03 CDT 2017',
        channelName: 'EXPCOM-WEB',
        jvmName: 'dtexpte4c2j1_02',
        requestUrl: 'http://dt-test4.jcpenney.com:80/expcom/j/homepage/?op=HotDeals4&expHomePage=true',
        maxAge: 1800,
        marketingHeadLine: 'Hot Deals 44444',
        marketingTagLine: 'Appliances HotSellers Picked for you',
        imagePath: 'hotdeals_4_181.png',
        seoUrl: null,
        certonaEnabled: false,
        dimensionId: '20000013, 1850',
        searchTerm: null,
        recordsInfoList: [
            {
                name: 'Liz ClaiborneÂ® Speckle Leaf Shower Curtain',
                marketingSlot: null,
                ppId: 'pp5004951544',
                currentMin: '24',
                currentMax: '24',
                originalMin: '24',
                originalMax: '24',
                priceType: 'everyday price',
                marketingLabel: null,
                url: null,
                reviewCount: '0',
                imageId: 'DP1231201417005544M.tif',
                colorizedImageId: 'DP1231201417005544M.tif',
                averageRating: '0.000000',
                currentPriceLabel: 'original',
                originalPriceLabel: null,
                altImageId: null,
                analyticsTag: 'rrec=true&rrplacementtype=norecs',
                currencyCode: 'USD',
            },
        ],
        type: 'HotDeals1',
        allDay: false,
        contentExpiry: 'Mon Aug 21 2017 03:29:56 AM',
        title: 'Hot Deals 4',
        shopAllTitle: null,
        hotDealsH1Tag: 'Shop Hot Deals',
        urlType: 'Internal',
        imageAlt: '',
        certonaStrategy: null,
        marketingTagLineColor: '#E9967A',
        backGroundColor: '#F08080',
        analyticsTag: 'cm_re=HP-hotdeals-_-norecs-_-Shop Hot Deals',
    },
    seoTitleTags: null,
};


const HotDealsNullResponse = {
    requestDateTime: 'Fri Jun 30 19:18:58 CDT 2017',
    channelName: 'EXPCOM-API',
    jvmName: 'dtexpte2l2j2_02',
    requestUrl: 'http://origin-apigw-dt-test2-web-l2.jcpenney.com:80/expcom-api/j/homepage?op=HotDeals1&dpAkamaiOverride=1&version=v5',
    maxAge: 0,
    position: 0,
    HotDeals1: {
        requestDateTime: 'Fri Jun 30 19:18:58 CDT 2017',
        channelName: 'EXPCOM-API',
        jvmName: 'dtexpte2l2j2_02',
        requestUrl: 'http://origin-apigw-dt-test2-web-l2.jcpenney.com:80/expcom-api/j/homepage?op=HotDeals1&dpAkamaiOverride=1&version=v5',
        maxAge: 2659261,
        marketingHeadLine: 'hot-deals-summer-essentials',
        marketingTagLine: 'Hot Deals1',
        imagePath: 'Cartridges_HotDeals.gif',
        seoUrl: '/g/mens-shirts/N-bwo3yD1nohp5?cm_re=test',
        certonaEnabled: false,
        dimensionId: '100240025',
        searchTerm: null,
        recordsInfoList: null,
        type: 'HotDeals1',
        allDay: false,
        contentExpiry: 'Mon Jul 31 2017 02:00:00 PM',
        title: 'Hot Deals1',
        shopAllTitle: 'SHOP NOW OR NEVER',
        hotDealsH1Tag: 'homepage-hot-deals-summer-essentials',
        urlType: 'Internal',
        imageAlt: '',
        certonaStrategy: null,
        marketingTagLineColor: '#e6ffe6',
        backGroundColor: '#ff6600',
    },
    seoTitleTags: null,
};

const HotDealsCertonaResponse = {
    requestDateTime: 'Fri Jun 30 19:18:58 CDT 2017',
    channelName: 'EXPCOM-API',
    jvmName: 'dtexpte2l2j2_02',
    requestUrl: 'http://origin-apigw-dt-test2-web-l2.jcpenney.com:80/expcom-api/j/homepage?op=HotDeals1&dpAkamaiOverride=1&version=v5',
    maxAge: 0,
    position: 0,
    HotDeals1: {
        requestDateTime: 'Fri Jun 30 19:18:58 CDT 2017',
        channelName: 'EXPCOM-API',
        jvmName: 'dtexpte2l2j2_02',
        requestUrl: 'http://origin-apigw-dt-test2-web-l2.jcpenney.com:80/expcom-api/j/homepage?op=HotDeals1&dpAkamaiOverride=1&version=v5',
        maxAge: 2659261,
        marketingHeadLine: 'hot-deals-summer-essentials',
        marketingTagLine: 'Hot Deals1',
        imagePath: 'Cartridges_HotDeals.gif',
        seoUrl: '/g/mens-shirts/N-bwo3yD1nohp5',
        certonaEnabled: true,
        dimensionId: '100240025',
        searchTerm: null,
        type: 'HotDeals1',
        allDay: false,
        contentExpiry: 'Mon Jul 31 2017 02:00:00 PM',
        title: 'Hot Deals1',
        shopAllTitle: 'SHOP NOW OR NEVER',
        hotDealsH1Tag: 'homepage-hot-deals-summer-essentials',
        urlType: 'Internal',
        imageAlt: '',
        certonaStrategy: 'home1_rr',
        marketingTagLineColor: '#e6ffe6',
        backGroundColor: '#ff6600',
    },
    seoTitleTags: null,
};

const CertonaResponse =
    {
        header: 'Top Sellers',
        items: [
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0908201617430787M.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater',
                price: '$14.99',
                originalPrice: '$44',
                id: 1,
                key: 1,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP1024201620363090C.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 2',
                price: '$15.99',
                originalPrice: '$54',
                id: 2,
                key: 2,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0816201620323546C.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 3',
                price: '$16.99',
                originalPrice: '$74',
                id: 3,
                key: 3,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0905201617112988M.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 4',
                price: '$18.99',
                originalPrice: '$84',
                id: 4,
                key: 4,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0811201617224082M.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 5',
                price: '$9 - $24',
                originalPrice: '$36',
                id: 5,
                key: 5,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0921201620435078C.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 6',
                price: '$9 - $32',
                originalPrice: '$46',
                id: 6,
                key: 6,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0927201617213506M.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 7',
                price: '$9 - $33',
                originalPrice: '$56',
                id: 7,
                key: 7,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0830201620460570C.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 8',
                price: '$9 - $56',
                originalPrice: '$86',
                id: 8,
                key: 8,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0908201617430787M.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater',
                price: '$14.99',
                originalPrice: '$44',
                id: 1,
                key: 1,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP1024201620363090C.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 2',
                price: '$15.99',
                originalPrice: '$54',
                id: 2,
                key: 2,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0816201620323546C.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 3',
                price: '$16.99',
                originalPrice: '$74',
                id: 3,
                key: 3,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
            {
                image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0905201617112988M.tif?$gallery$',
                title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 4',
                price: '$18.99',
                originalPrice: '$84',
                id: 4,
                key: 4,
                review: '(xxx)',
                sale: 'SALE',
                original: 'Original',
            },
        ],


    };

const cartridgeListResponse = [{
    name: 'Stafford® Travel Performance Super Shirt',
    marketingSlot: null,
    ppId: null,
    currentMin: '50',
    currentMax: '50',
    originalMin: '50',
    originalMax: '50',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-travel-performance-super-shirt/1cca9b9?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '1023',
    imageId: 'DP0506201417090669M.TIF',
    colorizedImageId: 'DP0924201420432132C.tif',
    averageRating: '4.31',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 4131,
    rating: '4.31',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0506201417090669M.TIF?wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-travel-performance-super-shirt/1cca9b9?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 50,
            max: 50,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 50,
            max: 50,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Travel Performance Super Shirt–Big & Tall',
    marketingSlot: null,
    ppId: null,
    currentMin: '60',
    currentMax: '60',
    originalMin: '60',
    originalMax: '60',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-travel-performance-super-shirtbig-tall/pp5002690070?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '1023',
    imageId: 'DP1027201617311372M.TIF',
    colorizedImageId: 'DP1110201620323112C.tif',
    averageRating: '4.31',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: 'DP0420201617050053M.TIF',
    currencyCode: 'USD',
    reviews: 4131,
    rating: '4.31',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP1027201617311372M.TIF?wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-travel-performance-super-shirtbig-tall/pp5002690070?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 60,
            max: 60,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 60,
            max: 60,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Travel Easy-Care Broadcloth Dress Shirt ',
    marketingSlot: null,
    ppId: null,
    currentMin: '36',
    currentMax: '36',
    originalMin: '36',
    originalMax: '36',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-travel-easy-care-broadcloth-dress-shirt/pp5003521148?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '1010',
    imageId: 'DP0206201317014857M.TIF',
    colorizedImageId: 'DP0408201520375858C.tif',
    averageRating: '4.38',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 4112,
    rating: '4.38',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0206201317014857M.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-travel-easy-care-broadcloth-dress-shirt/pp5003521148?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 36,
            max: 36,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 36,
            max: 36,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Arizona Solid Long-Sleeve Thermal Tee',
    marketingSlot: null,
    ppId: null,
    currentMin: '7.99',
    currentMax: '7.99',
    originalMin: '22',
    originalMax: '22',
    priceType: null,
    marketingLabel: null,
    url: '/p/arizona-solid-long-sleeve-thermal-tee/pp5005730148?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '64',
    imageId: 'DP0713201523242668C.TIF',
    colorizedImageId: '',
    averageRating: '4.58',
    currentPriceLabel: 'clearance',
    originalPriceLabel: 'original',
    altImageId: '',
    currencyCode: 'USD',
    reviews: 100,
    rating: '4.58',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0713201523242668C.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/arizona-solid-long-sleeve-thermal-tee/pp5005730148?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 22,
            max: 22,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 7.99,
            max: 7.99,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Van Heusen® No-Iron Lux Sateen Dress Shirt–Big & Tall',
    marketingSlot: null,
    ppId: null,
    currentMin: '50',
    currentMax: '50',
    originalMin: '50',
    originalMax: '50',
    priceType: null,
    marketingLabel: null,
    url: '/p/van-heusen-no-iron-lux-sateen-dress-shirtbig-tall/pp5005030688?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '24',
    imageId: '0900631B81E00B69M.TIF',
    colorizedImageId: 'DP0202201520370324C.tif',
    averageRating: '4.71',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 36,
    rating: '4.71',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/0900631B81E00B69M.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/van-heusen-no-iron-lux-sateen-dress-shirtbig-tall/pp5005030688?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 50,
            max: 50,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 50,
            max: 50,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Travel Wrinkle-Free Oxford Dress Shirt',
    marketingSlot: null,
    ppId: null,
    currentMin: '40',
    currentMax: '40',
    originalMin: '40',
    originalMax: '40',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-travel-wrinkle-free-oxford-dress-shirt/pp5003521141?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '1493',
    imageId: 'DP0410201520391929C.TIF',
    colorizedImageId: 'DP0311201620341639C.tif',
    averageRating: '4.48',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 5267,
    rating: '4.48',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0410201520391929C.TIF?wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-travel-wrinkle-free-oxford-dress-shirt/pp5003521141?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 40,
            max: 40,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 40,
            max: 40,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Executive Non-Iron Cotton Pinpoint Oxford Shirt',
    marketingSlot: null,
    ppId: null,
    currentMin: '50',
    currentMax: '60',
    originalMin: '60',
    originalMax: '60',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-executive-non-iron-cotton-pinpoint-oxford-shirt/pp5005030141?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '267',
    imageId: 'DP1210201520313820C.TIF',
    colorizedImageId: 'DP1210201520314127C.tif',
    averageRating: '4.31',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 615,
    rating: '4.31',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP1210201520313820C.TIF?wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-executive-non-iron-cotton-pinpoint-oxford-shirt/pp5005030141?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 60,
            max: 60,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 50,
            max: 60,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'St. John\'s Bay® Long-Sleeve Legacy Houndstooth Flannel Shirt',
    marketingSlot: null,
    ppId: null,
    currentMin: '6.79',
    currentMax: '6.79',
    originalMin: '34',
    originalMax: '34',
    priceType: null,
    marketingLabel: null,
    url: '/p/st-johns-bay-long-sleeve-legacy-houndstooth-flannel-shirt/pp5005141859?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '27',
    imageId: 'DP0611201520434288C.TIF',
    colorizedImageId: '',
    averageRating: '4.63',
    currentPriceLabel: 'clearance',
    originalPriceLabel: 'original',
    altImageId: '',
    currencyCode: 'USD',
    reviews: 39,
    rating: '4.63',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0611201520434288C.TIF?wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/st-johns-bay-long-sleeve-legacy-houndstooth-flannel-shirt/pp5005141859?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 34,
            max: 34,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 6.79,
            max: 6.79,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Travel Short-Sleeve Wrinkle-Free Oxford Shirt–Big & Tall',
    marketingSlot: null,
    ppId: null,
    currentMin: '46',
    currentMax: '46',
    originalMin: '46',
    originalMax: '46',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-travel-short-sleeve-wrinkle-free-oxford-shirtbig-tall/pp5002690051?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '51',
    imageId: 'DP0913201617450414M.TIF',
    colorizedImageId: '163BE43_0B5ABA5_531-2675_ECRU_JPG.tif',
    averageRating: '4.69',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: 'DP0913201617450414M.TIF',
    currencyCode: 'USD',
    reviews: 81,
    rating: '4.69',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0913201617450414M.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-travel-short-sleeve-wrinkle-free-oxford-shirtbig-tall/pp5002690051?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 46,
            max: 46,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 46,
            max: 46,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Executive Non-Iron Cotton Pinpoint Oxford Dress Shirt',
    marketingSlot: null,
    ppId: null,
    currentMin: '60',
    currentMax: '60',
    originalMin: '60',
    originalMax: '60',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-executive-non-iron-cotton-pinpoint-oxford-dress-shirt/pp5006170156?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '2',
    imageId: 'DP1009201517032702M.TIF',
    colorizedImageId: 'DP0316201620481605C.tif',
    averageRating: '5.0',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 2,
    rating: '5.0',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP1009201517032702M.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-executive-non-iron-cotton-pinpoint-oxford-dress-shirt/pp5006170156?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 60,
            max: 60,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 60,
            max: 60,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Travel Wrinkle-Free Oxford Dress Shirt–Big & Tall',
    marketingSlot: null,
    ppId: null,
    currentMin: '50',
    currentMax: '50',
    originalMin: '50',
    originalMax: '50',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-travel-wrinkle-free-oxford-dress-shirtbig-tall/pp5002701575?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '1493',
    imageId: 'DP1106201520403206C.TIF',
    colorizedImageId: 'DP1106201520403098C.tif',
    averageRating: '4.48',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 5267,
    rating: '4.48',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP1106201520403206C.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-travel-wrinkle-free-oxford-dress-shirtbig-tall/pp5002701575?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 50,
            max: 50,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 50,
            max: 50,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Travel Short-Sleeve Easy-Care Broadcloth Shirt–Big & Tall',
    marketingSlot: null,
    ppId: null,
    currentMin: '46',
    currentMax: '46',
    originalMin: '46',
    originalMax: '46',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-travel-short-sleeve-easy-care-broadcloth-shirtbig-tall/pp5002690050?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '271',
    imageId: 'DP1002201517022013M.TIF',
    colorizedImageId: 'DP0122201418381192C.tif',
    averageRating: '4.52',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 625,
    rating: '4.52',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP1002201517022013M.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-travel-short-sleeve-easy-care-broadcloth-shirtbig-tall/pp5002690050?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 46,
            max: 46,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 46,
            max: 46,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Travel Easy-Care Broadcloth Dress Shirt–Big & Tall ',
    marketingSlot: null,
    ppId: null,
    currentMin: '46',
    currentMax: '46',
    originalMin: '46',
    originalMax: '46',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-travel-easy-care-broadcloth-dress-shirtbig-tall/pp5003790733?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '1010',
    imageId: 'DP0410201317020493M.TIF',
    colorizedImageId: 'DP0311201318015185C.tif',
    averageRating: '4.38',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 4112,
    rating: '4.38',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0410201317020493M.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-travel-easy-care-broadcloth-dress-shirtbig-tall/pp5003790733?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 46,
            max: 46,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 46,
            max: 46,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'JF J. Ferrar® Easy-Care Dress Shirt - Super Slim',
    marketingSlot: null,
    ppId: null,
    currentMin: '40',
    currentMax: '40',
    originalMin: '40',
    originalMax: '40',
    priceType: null,
    marketingLabel: null,
    url: '/p/jf-j-ferrar-easy-care-dress-shirt-super-slim/pp5003720534?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '37',
    imageId: 'DP0310201418494616C.TIF',
    colorizedImageId: 'DP0310201418494366C.tif',
    averageRating: '4.76',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 55,
    rating: '4.76',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0310201418494616C.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/jf-j-ferrar-easy-care-dress-shirt-super-slim/pp5003720534?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 40,
            max: 40,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 40,
            max: 40,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}, {
    name: 'Stafford® Essentials Broadcloth Dress Shirt - Big & Tall',
    marketingSlot: null,
    ppId: null,
    currentMin: '15.99',
    currentMax: '15.99',
    originalMin: '40',
    originalMax: '40',
    priceType: null,
    marketingLabel: null,
    url: '/p/stafford-essentials-broadcloth-dress-shirt-big-tall/pp5002720035?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    reviewCount: '1010',
    imageId: 'DP0311201318023419C.TIF',
    colorizedImageId: 'DP0221201418212472C.tif',
    averageRating: '4.38',
    currentPriceLabel: 'original',
    originalPriceLabel: null,
    altImageId: '',
    currencyCode: 'USD',
    reviews: 4112,
    rating: '4.38',
    id: null,
    imageURL: '//s7d1.scene7.com/is/image/JCPenney/DP0311201318023419C.TIF?\n                            wid=450&amp;hei=450&amp;op_sharpen=1',
    linkURL: '/p/stafford-essentials-broadcloth-dress-shirt-big-tall/pp5002720035?pTmplType=regular&catId=cat100240025&deptId=dept20000014',
    priceDetails: {
        amounts: [{
            min: 40,
            max: 40,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }, {
            min: 15.99,
            max: 15.99,
            type: 'ORIGINAL',
            minPercentOff: 0,
            maxPercentOff: 0,
        }],
    },
}];
export {
    HotDealsResponse,
    HotDealsCertonaResponse,
    CertonaResponse,
    cartridgeListResponse,
    HotDealsNullResponse,
    HotDealsSEOURLResponse,
};
