const LeftVisualNavMenuResponse = {
    'SHOP DEPARTMENTS': [
        {
            name: 'bed & bath',
            departmentId: '20000012',
            targetUrl: '/g/bed-and-bath/N-bwo3w?pageType=X2H2',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0214201717015522M.tif',
            imageId: '7215320_pp_tablet.jpg',
            pageType: 'X2H2',
        },
        {
            name: 'window treatments',
            departmentId: '2842930842',
            targetUrl: '/g/window/N-1b0lvh6?pageType=X2H2',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0402201317025914M.tif',
            imageId: '7318695_pp_tablet.jpg',
            pageType: 'X2H2',
        },
        {
            name: 'kitchen & dining',
            departmentId: '100240016',
            targetUrl: '/g/kitchen-dining/N-bwo3vD1nohow?pageType=X2H2',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0202201317052031M.tif',
            imageId: 'kd_smalles.jpg',
            pageType: 'X2H2',
        },
        {
            name: 'furniture',
            departmentId: '100240019',
            targetUrl: '/g/furniture-store/N-bwo3vD1nohoz?pageType=X2H2',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP1114201417015077M.tif',
            imageId: 'fth_furn.jpg',
            pageType: 'X2H2',
        },
        {
            name: 'mattresses',
            departmentId: '100240132',
            targetUrl: '/g/mattresses/N-bwo3vD1nohs4',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: 'mattresses_tablet_category.jpg',
            pageType: 'XGN',
        },
        {
            name: 'rugs',
            departmentId: '100240023',
            targetUrl: '/g/rugs/N-bwo3vD1nohp3',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0217201417111894M.tif',
            imageId: 'fth_rugs.jpg',
            pageType: 'XGN',
        },
        {
            name: 'home decor',
            departmentId: '100240022',
            targetUrl: '/g/home-decor/N-bwo3vD1nohp2?pageType=X2H2',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0310201417145649M.tif',
            imageId: 'hd_mirrors.jpg',
            pageType: 'X2H2',
        },
        {
            name: 'patio & outdoor living',
            departmentId: '100210002',
            targetUrl: '/g/patio-furniture-sets/N-bwo3vD1nnuj6',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0122201417221270M.tif',
            imageId: 'f-patio.jpg',
            pageType: 'XGN',
        },
        {
            name: 'appliances',
            departmentId: '2846220841',
            targetUrl: '/g/appliances/N-1b2ke21?pageType=X2H2',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0107201603180430M.tif',
            imageId: 'a_fridge.jpg',
            pageType: 'X2H2',
        },
        {
            name: 'luggage',
            departmentId: '100210003',
            targetUrl: '/g/luggage/N-bwo3vD1nnuj7',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0131201317024912M.tif',
            imageId: 'fth_luggage.jpg',
            pageType: 'XGN',
        },
        {
            name: 'holiday decor',
            departmentId: '1002110011',
            targetUrl: '/g/holiday-decor/N-bwo3vDgkmp17',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0129201617094919M.tif',
            imageId: 'fth_4th.jpg',
            pageType: 'XGN',
        },
    ],
    'IN-HOME SERVICES': [
        {
            name: 'jcpenney home services',
            departmentId: null,
            targetUrl: 'https://jcpenney.myhomeprojectcenter.com/',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: 'jcpenney home services',
            imageUrl: null,
            imageId: 'JCPHomeServices_pp_tablet.gif',
            pageType: null,
        },
        {
            name: 'in-home custom window',
            departmentId: null,
            targetUrl: '/jsp/browse/marketing/promotion.jsp?pageId=pg40064400006',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: 'in-home custom window',
            imageUrl: null,
            imageId: 'CustomWindow_pp_tablet.jpg',
            pageType: null,
        },
    ],
    'FEATURED CATEGORIES': [
        {
            name: 'college life',
            departmentId: '1001360006',
            targetUrl: '/g/dorm-bedding-decor/N-bwo3vDgk6mbq',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0211201617034848M.tif',
            imageId: 'fth_dorm.jpg',
            pageType: 'XGN',
        },
        {
            name: 'wall decor',
            departmentId: '100240137',
            targetUrl: '/g/wall-decor/N-bwo3vD1nohs9',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP1228201517124927M.tif',
            imageId: 'hd_walldecor.jpg',
            pageType: 'XGN',
        },
        {
            name: 'smart home',
            departmentId: '1008220001',
            targetUrl: '/g/smart-home/N-bwo3vDgo9nj5',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0310201717174581M.tif',
            imageId: 'fth_smart.jpg',
            pageType: 'XGN',
        },
        {
            name: 'storage & organization',
            departmentId: '1002320013',
            targetUrl: '/g/storage-organization/N-bwo3vDgkr72l',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP1007201317125361M.tif',
            imageId: 'hd_storage.jpg',
            pageType: 'XGN',
        },
        {
            name: 'sheets',
            departmentId: '100250068',
            targetUrl: '/g/sheets/N-bwo3wD1nopg4',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0129201317024459M.tif',
            imageId: 'fth_sheets.jpg',
            pageType: 'XGN',
        },
        {
            name: 'as seen on tv',
            departmentId: '20000011, 4294967020',
            targetUrl: '/g/as-seen-on-tv-home-store/N-bwo3vZ1z141rg',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: 'AsSeenonTV_pp_tablet.jpg',
            pageType: 'XGN',
        },
        {
            name: 'electronics',
            departmentId: '100300092',
            targetUrl: '/g/home-electronics/N-bwo3vD1nps1o',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0828201217125015M.tif',
            imageId: 'fth_electronics.jpg',
            pageType: 'XGN',
        },
        {
            name: 'arts & crafts',
            departmentId: '1003040022',
            targetUrl: '/g/arts-crafts/N-bwo3vDgl6mmu',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0311201317010515M.tif',
            imageId: 'fth_arts.jpg',
            pageType: 'XGN',
        },
        {
            name: 'home improvement',
            departmentId: '1006070063',
            targetUrl: '/g/home-improvement/N-bwo3vDgmzkmn',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0827201517254454M.tif',
            imageId: 'fth_homeimpr.jpg',
            pageType: 'XGN',
        },
        {
            name: 'sporting goods & recreation',
            departmentId: '1006100004',
            targetUrl: '/g/sporting-goods-bicycles/N-bwo3vDgn07qc',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0921201517054960M.tif',
            imageId: 'fth_sports.jpg',
            pageType: 'XGN',
        },
        {
            name: 'camping & outdoor gear',
            departmentId: '1005540005',
            targetUrl: '/g/camping-outdoor-gear/N-bwo3vDgmo7mt',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0615201517020251M.tif',
            imageId: 'fth_camp.jpg',
            pageType: 'XGN',
        },
        {
            name: 'books & games',
            departmentId: '1003320009',
            targetUrl: '/g/board-games-cookbooks/N-bwo3vDglcmo9',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0904201317090950M.tif',
            imageId: 'fth_book.jpg',
            pageType: 'XGN',
        },
        {
            name: 'musical instruments',
            departmentId: '1006240008',
            targetUrl: '/g/musical-instruments/N-bwo3vDgn37rc',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0529201417091661M.tif',
            imageId: 'fth_music.jpg',
            pageType: 'XGN',
        },
        {
            name: 'heating & cooling',
            departmentId: '100440005',
            targetUrl: '/g/fans-air-purifiers/N-bwo3vD1nss05',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0723201317124600M.tif',
            imageId: 'a_fan.jpg',
            pageType: 'XGN',
        },
        {
            name: 'salon',
            departmentId: '2846290839',
            targetUrl: '/g/salon/N-1b2lw2f?pageType=X2H2',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP1205201619311711M.tif',
            imageId: 'fth_salon.jpg',
            pageType: 'X2H2',
        },
        {
            name: 'backpacks',
            departmentId: '100300083',
            targetUrl: '/g/backpacks-messenger-bags/N-bwo3vD1nps1f',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP0326201317010513M.tif',
            imageId: 'fth_backpack.jpg',
            pageType: 'XGN',
        },
        {
            name: 'auto accessories',
            departmentId: '1008340002',
            targetUrl: '/g/auto-accessories/N-bwo3vDgoc84i',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: 'fth_auto.jpg',
            pageType: 'XGN',
        },
        {
            name: 'party supplies',
            departmentId: '1008340001',
            targetUrl: '/g/party-supplies/N-bwo3vDgoc84h',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
    ],
    'SHOP SALE & CLEARANCE': [
        {
            name: 'sale',
            departmentId: '20000011, 1850',
            targetUrl: '/g/sale-home-store/N-bwo3vZ1fe',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: 'sale tablet icon.gif',
            pageType: 'XGN',
        },
        {
            name: 'buy more and save',
            departmentId: '20000011, 1851',
            targetUrl: '/g/buy-more-and-save-home-store/N-bwo3vZ1ff',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'closeouts',
            departmentId: '20000011, 4294921039',
            targetUrl: '/g/closeout-home-store/N-bwo3vZ1z132a7',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'clearance',
            departmentId: '20000011, 1849',
            targetUrl: '/g/clearance-home-store/N-bwo3vZ1fd',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: 'clearance logo tablet icon.gif',
            pageType: 'XGN',
        },
    ],
    'FEATURED BRANDS': [
        {
            name: 'bali',
            departmentId: null,
            targetUrl: 'http://baliblinds.jcpenney.com/',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: 'bali',
            imageUrl: null,
            imageId: ' ',
            pageType: null,
        },
        {
            name: 'calphalon',
            departmentId: '20000011, 1616',
            targetUrl: '/g/calphalon-home-store/N-bwo3vZ18w',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'cooks',
            departmentId: '20000011, 1254',
            targetUrl: '/g/cooks-home-store/N-bwo3vZyu',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'cuisinart',
            departmentId: '100240016, 180',
            targetUrl: '/g/cuisinart-kitchen-dining/N-bwo3vD1nohowZ50',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'dyson',
            departmentId: '20000011, 628',
            targetUrl: '/g/dyson-home-store/N-bwo3vZhg',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'jcpenney home',
            departmentId: '20000011, 1584',
            targetUrl: '/g/jcpenney-home-home-store/N-bwo3vZ180',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'keurig',
            departmentId: '100240016, 1102',
            targetUrl: '/g/keurig-kitchen-dining/N-bwo3vD1nohowZum',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'kitchenaid',
            departmentId: '100240016, 216',
            targetUrl: '/g/kitchen-aid-kitchen-dining/N-bwo3vD1nohowZ60',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'liz claiborne',
            departmentId: '20000011, 224',
            targetUrl: '/g/liz-claiborne-home-store/N-bwo3vZ68',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'royal velvet',
            departmentId: '20000011, 1639',
            targetUrl: '/g/royal-velvet-home-store/N-bwo3vZ19j',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'samsonite',
            departmentId: '100210003, 259',
            targetUrl: '/g/samsonite-luggage/N-bwo3vD1nnuj7Z77',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'sealy',
            departmentId: '100240019, 260',
            targetUrl: '/g/sealy-furniture-store/N-bwo3vD1nohozZ78',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'serta',
            departmentId: '100240019, 648',
            targetUrl: '/g/serta-furniture-store/N-bwo3vD1nohozZi0',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'shark',
            departmentId: '20000011, 1191',
            targetUrl: '/g/shark-home-store/N-bwo3vZx3',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
        {
            name: 'signature design by ashley',
            departmentId: '20000011, 4294300638',
            targetUrl: '/g/signature-design-by-ashley-home-store/N-bwo3vZ1z0prku',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: ' ',
            pageType: 'XGN',
        },
    ],
    'MORE WAYS TO SHOP': [
        {
            name: 'hospitality shop',
            departmentId: '1007430001',
            targetUrl: '/g/hospitality-shop/N-bwo3vDgnspyp',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: 'DP1011201317065855M.tif',
            imageId: 'fth_hospit.jpg',
            pageType: 'XGN',
        },
        {
            name: 'kids & teen rooms',
            departmentId: '20000011, 2006, 2007, 2010',
            targetUrl: '/g/kids-home-store/N-bwo3vZ1jqZ1jrZ1ju',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: null,
            imageUrl: null,
            imageId: 'f_kids.jpg',
            pageType: 'XGN',
        },
        {
            name: 'sports fan shop',
            departmentId: null,
            targetUrl: 'http://sportsfanshop.jcpenney.com/pages/Home_Decor/source/bm-JCP_HMSCL',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: 'sports fan shop',
            imageUrl: null,
            imageId: 'SportsFanShop_pp_tablet.jpg',
            pageType: null,
        },
        {
            name: 'jcp portraits',
            departmentId: null,
            targetUrl: 'http://www.jcpportraits.com/',
            clearance: false,
            targetWindow: 'SW',
            rangeFilter: null,
            h1Title: 'jcp portraits',
            imageUrl: null,
            imageId: ' ',
            pageType: null,
        },
    ],
};

export default { LeftVisualNavMenuResponse };
