export const GET_SITE_USER_PROFILE = 'GET_SITE_USER_PROFILE';
export const GET_SITE_USER_PROFILE_SUCCESS = 'GET_SITE_USER_PROFILE_SUCCESS';
export const GET_SITE_USER_PROFILE_ERROR = 'GET_SITE_USER_PROFILE_ERROR';
export const GET_SITE_REWARDS_REQUEST = 'GET_SITE_REWARDS_REQUEST';
export const GET_SITE_REWARDS_REQUEST_SUCCESS = 'GET_SITE_REWARDS_REQUEST_SUCCESS';
export const GET_SITE_REWARDS_REQUEST_ERROR = 'GET_SITE_REWARDS_REQUEST_ERROR';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
