const ADDTOCART_SITE_REQUEST = 'ADDTOCART_SITE_REQUEST ';
const ADDTOCART_SITE_REQUEST_ERROR = 'ADDTOCART_SITE_REQUEST_ERROR';
const ADDTOCART_SITE_REQUEST_SUCCESS = 'ADDTOCART_SITE_REQUEST_SUCCESS';

const ADDTOCART_SITE_KEEPSHOPPING_ONCLICK = 'ADDTOCART_SITE_KEEPSHOPPING_ONCLICK';
const MYLIST_CART_ADD_ANALYTICS = 'MYLIST_CART_ADD_ANALYTICS';

export default {
    ADDTOCART_SITE_REQUEST,
    ADDTOCART_SITE_REQUEST_ERROR,
    ADDTOCART_SITE_REQUEST_SUCCESS,
    ADDTOCART_SITE_KEEPSHOPPING_ONCLICK,
    MYLIST_CART_ADD_ANALYTICS,
};
