export const SET_HEADER_STORE_AS_SELECTED = 'SET_HEADER_STORE_AS_SELECTED';
export const TOGGLE_STORE_TO_FILTER = 'TOGGLE_STORE_TO_FILTER';
export const RESET_SELECTED_STORES = 'RESET_SELECTED_STORES';
export const SET_STORES_TO_FILTER = 'SET_STORES_TO_FILTER';
