export const SLIDER_CATEGORY_LOAD_REQUEST = 'SLIDER_CATEGORY_LOAD_REQUEST';
export const SLIDER_HOVER_LOAD_REQUEST = 'SLIDER_HOVER_LOAD_REQUEST';
export const SLIDER_HOVER_LOAD_SUCCESS = 'SLIDER_HOVER_LOAD_SUCCESS';
export const SLIDER_CATEGORY_LOAD_SUCCESS = 'SLIDER_CATEGORY_LOAD_SUCCESS';
export const SLIDER_CATEGORY_LOAD_ERROR = 'SLIDER_CATEGORY_LOAD_ERROR';
