export const IRIS_TEMPLATE_LOAD_REQUEST = 'IRIS_TEMPLATE_LOAD_REQUEST';
export const IRIS_TEMPLATE_LOAD_SUCCESS = 'IRIS_TEMPLATE_LOAD_SUCCESS';
export const IRIS_TEMPLATE_LOAD_ERROR = 'IRIS_TEMPLATE_LOAD_ERROR';

