export const SAVED_ITEMS_LOAD_REQUEST = 'SAVED_ITEMS_LOAD_REQUEST';
export const SAVED_ITEMS_LOAD_SUCCESS = 'SAVED_ITEMS_LOAD_SUCCESS';
export const SAVED_ITEMS_LOAD_ERROR = 'SAVED_ITEMS_LOAD_ERROR';
