export const ZONE_DATA_GET_REQUEST = 'ZONE_DATA_GET_REQUEST';
export const ZONE_DATA_GET_ALL_SUCCESS = 'ZONE_DATA_GET_SUCCESS';
export const ZONE_DATA_SPECIFIC_SUCCESS = 'ZONE_DATA_SPECIFIC_SUCCESS';
export const ZONE_DATA_CLEAR = 'ZONE_DATA_CLEAR';
