export const MARKETING_CONTENT_GET_REQUEST = 'MARKETING_CONTENT_GET_REQUEST';
export const MARKETING_CONTENT_GET_SUCCESS = 'MARKETING_CONTENT_GET_SUCCESS';
export const MARKETING_CONTENT_GET_ERROR = 'MARKETING_CONTENT_GET_ERROR';

