const NAVIGATION_MENU_GET_REQUEST = 'NAVIGATION_MENU_GET_REQUEST';
const NAVIGATION_MENU_GET_SUCCESS = 'NAVIGATION_MENU_GET_SUCCESS';
const NAVIGATION_MENU_GET_ERROR = 'NAVIGATION_MENU_GET_ERROR';
const NAVIGATION_MENU_ACTIVE_ONCLICK = 'NAVIGATION_MENU_ACTIVE_ONCLICK';
const NAVIGATION_MENU_ACTIVE_ONCLICK_GET_REQUEST = 'NAVIGATION_MENU_ACTIVE_ONCLICK_GET_REQUEST';
const NAVIGATION_MENU_ACTIVE_GET_SUCCESS = 'NAVIGATION_MENU_ACTIVE_GET_SUCCESS';
const NAVIGATION_MENU_ACTIVE_GET_ERROR = 'NAVIGATION_MENU_ACTIVE_GET_ERROR';
const NAVIGATION_MENU_PREVIOUS_ONCLICK = 'NAVIGATION_MENU_PREVIOUS_ONCLICK';

export default {
    NAVIGATION_MENU_GET_REQUEST,
    NAVIGATION_MENU_GET_SUCCESS,
    NAVIGATION_MENU_GET_ERROR,
    NAVIGATION_MENU_ACTIVE_ONCLICK,
    NAVIGATION_MENU_ACTIVE_ONCLICK_GET_REQUEST,
    NAVIGATION_MENU_ACTIVE_GET_SUCCESS,
    NAVIGATION_MENU_ACTIVE_GET_ERROR,
    NAVIGATION_MENU_PREVIOUS_ONCLICK,
};
