const PRODUCT_PROMOTION_LIST_GET_REQUEST = 'PRODUCT_PROMOTION_LIST_GET_REQUEST';
const PRODUCT_PROMOTION_LIST_GET_SUCCESS = 'PRODUCT_PROMOTION_LIST_GET_SUCCESS';
const PRODUCT_PROMOTION_LIST_GET_ERROR = 'PRODUCT_PROMOTION_LIST_GET_ERROR';
const PRODUCT_PROMOTION_LOAD_MORE_EVENT = 'PRODUCT_PROMOTION_LOAD_MORE_EVENT';
const PRODUCT_PROMOTION_LIST_CLEAR = 'PRODUCT_PROMOTION_LIST_CLEAR';

export {
    PRODUCT_PROMOTION_LIST_GET_REQUEST,
    PRODUCT_PROMOTION_LIST_GET_SUCCESS,
    PRODUCT_PROMOTION_LIST_GET_ERROR,
    PRODUCT_PROMOTION_LOAD_MORE_EVENT,
    PRODUCT_PROMOTION_LIST_CLEAR,
};
