export const PROMOTIONALBANNERDATA_GET_REQUEST = 'PROMOTIONALBANNERDATA_GET_REQUEST';
export const PROMOTIONALBANNERDATA_GET_SUCCESS = 'PROMOTIONALBANNERDATA_GET_SUCCESS';
export const PROMOTIONALBANNERDATA_GET_ERROR = 'PROMOTIONALBANNERDATA_GET_ERROR';
