export const SESSION_DELETE_REQUEST = 'SESSION_DELETE_REQUEST';
export const SESSION_DELETE_SUCCESS = 'SESSION_DELETE_SUCCESS';
export const SESSION_DELETE_ERROR = 'SESSION_DELETE_ERROR';
export const IS_SESSION_TIMED_OUT = 'IS_SESSION_TIMED_OUT';
