export default
{
    header: 'Top Sellers',
    items: [
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0908201617430787M.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater',
            price: '$14.99',
            originalPrice: '$44',
            id: 1,
            key: 1,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP1024201620363090C.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 2',
            price: '$15.99',
            originalPrice: '$54',
            id: 2,
            key: 2,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0816201620323546C.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 3',
            price: '$16.99',
            originalPrice: '$74',
            id: 3,
            key: 3,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0905201617112988M.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 4',
            price: '$18.99',
            originalPrice: '$84',
            id: 4,
            key: 4,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0811201617224082M.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 5',
            price: '$9 - $24',
            originalPrice: '$36',
            id: 5,
            key: 5,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0921201620435078C.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 6',
            price: '$9 - $32',
            originalPrice: '$46',
            id: 6,
            key: 6,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0927201617213506M.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 7',
            price: '$9 - $33',
            originalPrice: '$56',
            id: 7,
            key: 7,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0830201620460570C.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 8',
            price: '$9 - $56',
            originalPrice: '$86',
            id: 8,
            key: 8,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0908201617430787M.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater',
            price: '$14.99',
            originalPrice: '$44',
            id: 1,
            key: 1,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP1024201620363090C.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 2',
            price: '$15.99',
            originalPrice: '$54',
            id: 2,
            key: 2,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0816201620323546C.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 3',
            price: '$16.99',
            originalPrice: '$74',
            id: 3,
            key: 3,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
        {
            image: 'http://s7d9.scene7.com/is/image/JCPenney/DP0905201617112988M.tif?$gallery$',
            title: 'Liz Claiborne 3/4 Sleeve Crew Neck Pullover Sweater 4',
            price: '$18.99',
            originalPrice: '$84',
            id: 4,
            key: 4,
            review: '(xxx)',
            sale: 'SALE',
            original: 'Original',
        },
    ],


};
