
export const stores = [
    {
        id: '2795',
        title: 'Stonebriar Mall',
        addr: '2607 Preston Rd',
        city: 'Frisco',
        zip: '75034',
        phone: '(972) 712-2707',
        distance: 1.4,
        latitude: 33.09948,
        longitude: -96.80954,
        phoneNumber: '2795',
        country: null,
        state: 'TX',
        directionUrl: 'https://blah.com',
        timing: [
            'Mon-Sat: 10:00am-9:00pm',
            'Sun: 11:00am-7:00pm',
        ],
        availability: '',
        timingOverrideMessage: null,
        storeServices: [
            'big and tall',
            'major appliances',
            'custom decorating',
            'furniture',
            'wedding registry',
            'optical',
            'portrait studio',
            'salon',
            'Sephora',
            'jewelry',
        ],
    },
    {
        id: '2055',
        title: 'Collin Creek Mall',
        addr: '821 N Central Expwy',
        city: 'Plano',
        zip: '75075',
        phone: '(972) 578-8666',
        distance: 7.1,
        latitude: 33.01284,
        longitude: -96.71364,
        phoneNumber: '2055',
        country: null,
        directionUrl: 'https://blah.com',
        state: 'TX',
        timing: [
            'Mon-Sat: 10:00am-9:00pm',
            'Sun: 11:00am-7:00pm',
        ],
        availability: '',
        timingOverrideMessage: null,
        storeServices: [
            'big and tall',
            'major appliances',
            'custom decorating',
            'wedding registry',
            'optical',
            'portrait studio',
            'salon',
            'Sephora',
            'jewelry',
        ],
    },
    {
        id: '2982',
        title: 'Village @ Fairview',
        addr: '301 Stacy Rd',
        city: 'Fairview',
        zip: '75069',
        phone: '(972) 549-4094',
        distance: 10,
        latitude: 33.13107,
        longitude: -96.64784,
        phoneNumber: '2982',
        country: null,
        directionUrl: 'https://blah.com',
        availability: '',
        state: 'TX',
        timing: [
            'Mon-Sat: 10:00am-9:00pm',
            'Sun: 11:00am-7:00pm',
        ],
        timingOverrideMessage: null,
        storeServices: [
            'big and tall',
            'major appliances',
            'custom decorating',
            'furniture',
            'wedding registry',
            'portrait studio',
            'salon',
            'Sephora',
            'jewelry',
        ],
    },
    {
        id: '2410',
        title: 'Vista Ridge Mall',
        addr: '2401 S Stemmons Fwy  Ste 4000',
        city: 'Lewisville',
        zip: '75067',
        directionUrl: 'https://blah.com',
        phone: '(972) 315-3900',
        distance: 10.8,
        latitude: 33.00318,
        longitude: -96.97244,
        phoneNumber: '2410',
        country: null,
        state: 'TX',
        timing: [
            'Mon-Sat: 10:00am-9:00pm',
            'Sun: 11:00am-7:00pm',
        ],
        availability: '',
        timingOverrideMessage: null,
        storeServices: [
            'big and tall',
            'major appliances',
            'custom decorating',
            'wedding registry',
            'optical',
            'portrait studio',
            'salon',
            'jewelry',
        ],
    },
    {
        id: '0179',
        title: 'Timber Creek Crossng',
        addr: '6051 Skillman St',
        city: 'Dallas',
        directionUrl: 'https://blah.com',
        zip: '75231',
        phone: '(972) 892-2050',
        distance: 15.3,
        latitude: 32.86288,
        longitude: -96.75233,
        phoneNumber: '0179',
        country: null,
        state: 'TX',
        timing: [
            'Mon-Sat: 10:00am-9:00pm',
            'Sun: 11:00am-7:00pm',
        ],
        availability: '',
        timingOverrideMessage: 'Special Holiday Hours<p>Mon 6:00am-10:00pm</p><p>Tue-Fri 10:00am-9:00pm</p><p>Sat 10:00am-8:00pm</p><p>Sun 11:00am-8:00pm</p><p>(Note) Except where prohibited by law</p>',
        storeServices: [
            'big and tall',
            'major appliances',
            'custom decorating',
            'wedding registry',
            'portrait studio',
            'salon',
            'Sephora',
            'jewelry',
        ],
    },
];

export const center = {
    id: '0179',
    latitude: 32.86288,
    longitude: -96.75233,
};
